// WHITE PAPER 01 — "The Autonomous Intelligence Imperative"
//
// kind: 'paper', design: 'report' — the house treatment for every white paper. Shares the
// block model, registry, schema and sitemap with the journal articles; only the
// presentation and a few fields differ. Copy is VERBATIM from the approved draft.
//
// The governance material (sections 13 and 17, and the autonomy spectrum) is the paper's
// argument, not a compliance appendix: its whole thesis is that autonomy without
// governance is unmanaged automation. Do not trim it for length.
import type { Insight } from './types'

export const autonomousIntelligenceImperative: Insight = {
  slug: 'autonomous-intelligence-imperative',
  kind: 'paper',
  design: 'report',
  title: 'The Autonomous Intelligence Imperative',
  subtitle: 'From Automation to Systems That Perceive, Reason, Adapt and Act',
  seoTitle: 'The Autonomous Intelligence Imperative — SVARA Research White Paper',
  metaDescription:
    'A SVARA research white paper on the shift from automation to autonomous intelligence: the intelligence loop, the eight-layer stack, controlled autonomy, governance and a practical roadmap.',
  category: 'Deep Tech & Autonomous Intelligence',
  contentType: 'White Paper',
  searchIntent: 'Informational',
  readingTime: '30–40 minutes',
  extent: '30–40 pages',
  published: '2026-09-02',
  primaryKeywords: [
    'autonomous intelligence', 'autonomous intelligence architecture', 'AI white paper',
    'enterprise AI strategy', 'agentic AI enterprise', 'AI operating system',
  ],
  secondaryKeywords: [
    'AI maturity model', 'AI governance', 'controlled autonomy', 'digital twins',
    'AI agents', 'edge AI', 'vision AI', 'AI orchestration', 'autonomous enterprise',
  ],
  dek: 'The next generation of organisations will not simply use more AI. They will build systems in which intelligence can continuously perceive, understand, reason, simulate, coordinate and act.',

  corePosition: {
    heading: 'The Core Position',
    paragraphs: [
      'The central argument of this white paper is simple: the next generation of organisations will not simply use more AI. They will build systems in which intelligence can continuously perceive, understand, reason, simulate, coordinate and act.',
      'For decades, enterprise technology has largely been organised around applications, databases and workflows. The emerging architecture is different.',
      'Instead of asking people to continuously navigate between systems, interpret dashboards and manually coordinate action, intelligent systems can increasingly participate in the operational loop itself.',
      'The shift is from systems that store information, to systems that understand information — and eventually to systems that can participate in what happens next.',
      'This white paper will establish that transition as the Autonomous Intelligence Imperative.',
    ],
  },

  blocks: [
    { kind: 'h2', id: 'executive-summary', text: 'Executive Summary' },
    { kind: 'p', text: 'Artificial intelligence is changing the fundamental relationship between organisations and technology.' },
    { kind: 'p', text: 'The first generation of enterprise software was primarily designed to digitise information.' },
    { kind: 'p', text: 'The next generation automated workflows.' },
    { kind: 'p', text: 'Artificial intelligence introduced systems capable of recognising patterns, making predictions and generating content.' },
    { kind: 'p', text: 'Now, a new architectural possibility is emerging.' },
    { kind: 'p', text: 'Intelligence can begin participating directly in the operational cycle.' },
    { kind: 'p', text: 'An intelligent system may observe an environment through cameras, sensors, enterprise systems and user interactions. It can interpret what is happening. It can retrieve relevant context. It can reason about possible responses. It can simulate potential outcomes. It can coordinate specialised AI agents and software tools. And, within defined permissions, it can take action.' },
    { kind: 'p', text: 'This represents a progression from:' },
    { kind: 'flow', steps: ['Digitalisation', 'Automation', 'Intelligence', 'Agency', 'Autonomous Intelligence'] },
    { kind: 'p', text: 'The important distinction is that autonomous intelligence is not a single model, application or AI agent.' },
    { kind: 'statement', text: 'It is an intelligence architecture.' },
    { kind: 'p', text: 'It connects multiple capabilities into a continuous loop:' },
    { kind: 'defs', items: [
      { term: 'Perceive', text: 'What is happening?' },
      { term: 'Understand', text: 'What does it mean?' },
      { term: 'Contextualise', text: 'What else do we need to know?' },
      { term: 'Reason', text: 'What are the possible responses?' },
      { term: 'Simulate', text: 'What could happen?' },
      { term: 'Decide', text: 'What should happen next?' },
      { term: 'Act', text: 'What is permitted?' },
      { term: 'Observe', text: 'What happened?' },
      { term: 'Adapt', text: 'What should change next time?' },
    ] },
    { kind: 'p', text: 'The objective is not unrestricted AI autonomy.' },
    { kind: 'p', text: 'The objective is to create systems with the appropriate level of intelligence and autonomy for the environment in which they operate.' },
    { kind: 'p', text: 'That requires more than powerful AI models. It requires:' },
    { kind: 'ul', items: [
      'perception;', 'data;', 'context;', 'reasoning;', 'simulation;', 'agency;',
      'orchestration;', 'governance;', 'observability;', 'human oversight.',
    ] },
    { kind: 'p', text: 'This white paper introduces the SVARA Autonomous Intelligence Stack as a framework for understanding how these layers can work together.' },

    { kind: 'h2', id: 'end-of-software-only', text: 'The End of the Software-Only Era' },
    { kind: 'p', text: 'Modern organisations run on software.' },
    { kind: 'p', text: 'Every department uses systems to manage:' },
    { kind: 'ul', items: ['customers;', 'operations;', 'finance;', 'supply chains;', 'engineering;', 'employees;', 'communication;', 'infrastructure.'] },
    { kind: 'p', text: 'But there is a fundamental limitation.' },
    { kind: 'statement', text: 'Most software requires a person to decide what to do.' },
    { kind: 'p', text: 'A dashboard can show a problem. A human must notice it.' },
    { kind: 'p', text: 'A report can identify a trend. A human must interpret it.' },
    { kind: 'p', text: 'An alert can signal an anomaly. A human must investigate.' },
    { kind: 'p', text: 'Multiple systems may contain the information required to make a decision. A human must connect them.' },
    { kind: 'p', text: 'The organisation therefore develops an increasingly complex relationship with information.' },
    { kind: 'ul', items: [
      'More software does not necessarily mean more understanding.',
      'More dashboards do not necessarily mean faster decisions.',
      'More data does not necessarily mean greater intelligence.',
    ] },
    { kind: 'p', text: 'The next architectural challenge is not simply: how do we generate more information?' },
    { kind: 'statement', text: 'It is: how do we transform information into understanding, and understanding into appropriate action?' },
    { kind: 'p', text: 'That is where autonomous intelligence begins.' },

    { kind: 'h2', id: 'from-automation', text: 'From Automation to Autonomous Intelligence' },
    { kind: 'p', text: 'The evolution can be understood through five major stages.' },
    { kind: 'h3', id: 'stage-01-software', text: 'Stage 01 — Software' },
    { kind: 'flow', steps: ['Input', 'Rule', 'Output'] },
    { kind: 'p', text: 'Traditional software executes explicit instructions. If a defined condition occurs, the system performs a predefined function. The logic is deterministic.' },
    { kind: 'h3', id: 'stage-02-automation', text: 'Stage 02 — Automation' },
    { kind: 'flow', steps: ['Trigger', 'Workflow', 'Action'] },
    { kind: 'p', text: 'Automation connects multiple tasks. For example: customer submits a request → CRM creates a record → notification is sent → task is assigned.' },
    { kind: 'p', text: 'The workflow can be sophisticated. But the logic is largely predetermined.' },
    { kind: 'h3', id: 'stage-03-ai', text: 'Stage 03 — Artificial Intelligence' },
    { kind: 'flow', steps: ['Data', 'Pattern Recognition', 'Prediction / Classification'] },
    { kind: 'p', text: 'AI introduces the ability to work with patterns and uncertainty. Systems can potentially:' },
    { kind: 'ul', items: ['recognise objects;', 'classify information;', 'detect anomalies;', 'forecast outcomes;', 'generate predictions.'] },
    { kind: 'h3', id: 'stage-04-agentic', text: 'Stage 04 — Agentic Systems' },
    { kind: 'flow', steps: ['Goal', 'Reasoning', 'Tool Use', 'Evaluation'] },
    { kind: 'p', text: 'AI agents introduce goal-oriented behaviour. The system may:' },
    { kind: 'ul', items: [
      'interpret an objective;', 'retrieve information;', 'determine a sequence of steps;',
      'use software tools;', 'evaluate progress;', 'continue toward an outcome.',
    ] },
    { kind: 'h3', id: 'stage-05-autonomous', text: 'Stage 05 — Autonomous Intelligence' },
    { kind: 'flow', steps: ['Perception', 'Context', 'Reasoning', 'Simulation', 'Agency', 'Action', 'Feedback'] },
    { kind: 'p', text: 'Autonomous intelligence connects these capabilities into an adaptive system.' },
    { kind: 'p', text: 'The system is no longer only responding to a single prompt or trigger. It can participate in a continuous operational loop.' },

    { kind: 'h2', id: 'defining', text: 'Defining Autonomous Intelligence' },
    { kind: 'p', text: 'SVARA defines autonomous intelligence as:' },
    { kind: 'statement', text: 'An interconnected intelligence architecture capable of perceiving information, understanding context, reasoning about possible outcomes and taking or coordinating action within defined objectives, permissions and governance boundaries.' },
    { kind: 'p', text: 'There are five important elements in this definition.' },
    { kind: 'defs', items: [
      { term: '1. Interconnected', text: 'Autonomous intelligence is not one isolated AI model. It connects multiple intelligence and operational systems.' },
      { term: '2. Context-Aware', text: 'Information must be understood within its environment.' },
      { term: '3. Adaptive', text: 'The system can respond to changing conditions.' },
      { term: '4. Action-Oriented', text: 'The system can move beyond analysis toward coordination and execution.' },
      { term: '5. Governed', text: 'Every capability must operate within defined boundaries.' },
    ] },
    { kind: 'p', text: 'This final element is critical.' },
    { kind: 'statement', text: 'Autonomy without governance is not intelligence. It is unmanaged automation with greater uncertainty.' },

    { kind: 'h2', id: 'the-loop', text: 'The Autonomous Intelligence Loop' },
    { kind: 'p', text: 'The fundamental architecture can be represented as a continuous cycle.' },
    { kind: 'defs', items: [
      { term: '01. Perceive', text: 'Gather information from cameras, sensors, IoT devices, enterprise applications, documents, APIs, databases and user interactions. Question: what is happening?' },
      { term: '02. Understand', text: 'Interpret the information. Question: what does it mean?' },
      { term: '03. Contextualise', text: 'Connect the information with relevant history, systems, relationships and constraints. Question: what else matters?' },
      { term: '04. Reason', text: 'Evaluate possible explanations and responses. Question: what are the available options?' },
      { term: '05. Simulate', text: 'Where appropriate, model possible consequences. Question: what could happen next?' },
      { term: '06. Decide', text: 'Select an appropriate response. Question: what should we do?' },
      { term: '07. Act', text: 'Execute an approved action or escalate to a human. Question: what are we permitted to do?' },
      { term: '08. Observe', text: 'Measure the outcome. Question: what happened?' },
      { term: '09. Adapt', text: 'Use the new information to improve subsequent decisions. Question: what should change?' },
    ] },
    { kind: 'p', text: 'Then the cycle begins again.' },

    { kind: 'h2', id: 'the-stack', text: 'The SVARA Autonomous Intelligence Stack' },
    { kind: 'p', text: 'The SVARA framework organises autonomous intelligence into eight connected layers.' },
    { kind: 'stack', layers: [
      { name: 'Layer 01 — Perception', items: ['Vision AI', 'Sensors', 'IoT', 'Enterprise Data', 'Edge Intelligence'] },
      { name: 'Layer 02 — Context', items: ['Knowledge Systems', 'Data Infrastructure', 'Context Engineering', 'Digital Twins', 'Enterprise Knowledge'] },
      { name: 'Layer 03 — Intelligence', items: ['Generative AI', 'Cognitive AI', 'Machine Learning', 'Predictive Intelligence', 'Multimodal AI'] },
      { name: 'Layer 04 — Simulation', items: ['Digital Twins', 'Scenario Modelling', 'Predictive Simulation', 'Synthetic Environments'] },
      { name: 'Layer 05 — Agency', items: ['AI Agents', 'Multi-Agent Systems', 'Tool Use', 'Agentic Workflows'] },
      { name: 'Layer 06 — Orchestration', items: ['AI OS', 'Model Orchestration', 'Agent Orchestration', 'Workflow Intelligence', 'Governance Systems'] },
      { name: 'Layer 07 — Action', items: ['Enterprise Software', 'Automation', 'APIs', 'Machines', 'Robotics', 'Human Teams'] },
      { name: 'Layer 08 — Adaptation', items: ['Feedback Loops', 'Monitoring', 'Evaluation', 'Optimisation', 'Continuous Improvement'] },
    ] },

    { kind: 'h2', id: 'perception', text: 'Perception: Understanding the Environment' },
    { kind: 'p', text: 'Intelligence begins with information.' },
    { kind: 'p', text: 'An organisation cannot reason effectively about an environment it cannot observe.' },
    { kind: 'p', text: 'In autonomous intelligence systems, perception may come from both the physical and digital world.' },
    { kind: 'defs', items: [
      { term: 'Physical perception', text: 'cameras, sensors, machines, drones and connected devices.' },
      { term: 'Digital perception', text: 'applications, transactions, databases, APIs, documents and communications.' },
    ] },
    { kind: 'p', text: 'Vision AI introduces a particularly important capability. Machines can begin extracting structured information from visual environments.' },
    { kind: 'p', text: 'Edge AI can move selected intelligence closer to where information is generated.' },
    { kind: 'p', text: 'This can reduce the distance between event and intelligence.' },

    { kind: 'h2', id: 'context', text: 'Context: Turning Data Into Understanding' },
    { kind: 'p', text: 'Data is not understanding.' },
    { kind: 'p', text: 'Consider this event: equipment temperature has increased by 14%.' },
    { kind: 'p', text: 'Without context, the system does not know whether this matters.' },
    { kind: 'p', text: 'Context could reveal:' },
    { kind: 'ul', items: [
      'the equipment recently changed operating modes;', 'ambient temperature increased;',
      'maintenance is overdue;', 'production demand increased;', 'the sensor may be malfunctioning.',
    ] },
    { kind: 'p', text: 'The same data point can therefore lead to entirely different decisions.' },
    { kind: 'p', text: 'Autonomous intelligence requires systems capable of connecting information across:' },
    { kind: 'ul', items: ['time;', 'processes;', 'assets;', 'people;', 'applications;', 'environments.'] },
    { kind: 'p', text: 'Digital twins can provide an important contextual layer. They create structured representations of physical or operational systems and their relationships.' },
    { kind: 'statement', text: 'Context answers: what does this information mean in this particular situation?' },

    { kind: 'h2', id: 'intelligence', text: 'Intelligence: Reasoning Beyond Rules' },
    { kind: 'p', text: 'Traditional automation relies heavily on predetermined rules.' },
    { kind: 'p', text: 'Autonomous intelligence introduces the possibility of evaluating context dynamically.' },
    { kind: 'p', text: 'Instead of IF X → DO Y, the system may ask:' },
    { kind: 'ul', items: [
      'What happened?', 'Why might it have happened?', 'What information is missing?',
      'What options are available?', 'What are the consequences of each option?',
    ] },
    { kind: 'p', text: 'Generative and cognitive AI can support this reasoning layer.' },
    { kind: 'p', text: 'However, intelligence should not rely on a single model alone. The architecture may combine:' },
    { kind: 'ul', items: ['AI models;', 'rules;', 'knowledge systems;', 'retrieval;', 'predictive models;', 'simulations.'] },
    { kind: 'p', text: 'The objective is not simply to generate an answer.' },
    { kind: 'statement', text: 'The objective is to support an appropriate decision.' },

    { kind: 'h2', id: 'simulation', text: 'Simulation: Exploring Possible Futures' },
    { kind: 'p', text: 'One of the most significant capabilities within autonomous intelligence is the ability to evaluate possibilities before acting.' },
    { kind: 'p', text: 'Simulation allows systems to explore:' },
    { kind: 'ul', items: [
      'What happens if we do nothing?', 'What happens if we take Action A?',
      'What happens if conditions continue changing?',
    ] },
    { kind: 'p', text: 'Digital twins can provide contextual models. Simulation can explore scenarios. AI can interpret the results. Agents can coordinate responses.' },
    { kind: 'p', text: 'This creates an architecture where intelligence does not simply react. It can potentially evaluate possible futures.' },
    { kind: 'statement', text: 'The ability to simulate before acting may become one of the defining characteristics of advanced autonomous systems.' },

    { kind: 'h2', id: 'agency', text: 'Agency: AI Systems That Can Take Action' },
    { kind: 'p', text: 'Understanding a problem does not solve it.' },
    { kind: 'p', text: 'A system must eventually connect intelligence with action.' },
    { kind: 'p', text: 'AI agents introduce this capability. An agent can potentially:' },
    { kind: 'ul', items: [
      'receive an objective;', 'gather information;', 'access authorised tools;',
      'execute workflows;', 'evaluate results;', 'continue working toward an outcome.',
    ] },
    { kind: 'p', text: 'A multi-agent architecture may involve specialised agents. For example:' },
    { kind: 'stack', layers: [
      { name: 'Analyst Agent', items: ['Investigates the event'] },
      { name: 'Data Agent', items: ['Retrieves relevant information'] },
      { name: 'Simulation Agent', items: ['Explores possible scenarios'] },
      { name: 'Decision Agent', items: ['Evaluates permitted actions'] },
      { name: 'Execution Agent', items: ['Performs approved actions'] },
    ] },
    { kind: 'p', text: 'This creates a distributed intelligence architecture.' },
    { kind: 'p', text: 'However, agency must always be connected to permissions.' },
    { kind: 'statement', text: 'An agent should not simply ask what it can do. It must also understand what it is allowed to do.' },

    { kind: 'h2', id: 'orchestration', text: 'Orchestration: The Role of AI OS' },
    { kind: 'p', text: 'As organisations deploy more AI capabilities, a new problem emerges: how do they all work together?' },
    { kind: 'p', text: 'An enterprise may eventually operate:' },
    { kind: 'ul', items: [
      'hundreds of AI models;', 'specialised agents;', 'knowledge systems;',
      'automation workflows;', 'digital twins;', 'external AI services;', 'internal software systems.',
    ] },
    { kind: 'p', text: 'Without orchestration, intelligence becomes fragmented.' },
    { kind: 'p', text: 'AI OS can become the coordination layer. Its role may include:' },
    { kind: 'ul', items: [
      'agent orchestration;', 'model selection;', 'context management;', 'permissions;',
      'workflow coordination;', 'monitoring;', 'observability;', 'governance.',
    ] },
    { kind: 'p', text: 'The AI OS is not necessarily one application.' },
    { kind: 'statement', text: 'It is the operating architecture through which intelligence is coordinated across the organisation.' },

    { kind: 'h2', id: 'controlled-autonomy', text: 'Human Oversight and Controlled Autonomy' },
    { kind: 'p', text: 'The goal should never be maximum autonomy by default.' },
    { kind: 'p', text: 'The appropriate level depends on:' },
    { kind: 'ul', items: ['risk;', 'operational impact;', 'reversibility;', 'confidence;', 'regulation;', 'organisational policy.'] },
    { kind: 'p', text: 'SVARA proposes a spectrum.' },
    { kind: 'scale',
      caption: 'The autonomy spectrum',
      levels: [
        { label: 'Level 01 — Observe', text: 'The system presents information.' },
        { label: 'Level 02 — Recommend', text: 'The system proposes possible actions.' },
        { label: 'Level 03 — Assist', text: 'The system performs tasks with human approval.' },
        { label: 'Level 04 — Execute Within Boundaries', text: 'The system performs predefined categories of low-risk actions independently.' },
        { label: 'Level 05 — Adaptive Coordination', text: 'The system dynamically coordinates intelligence and actions within strict governance constraints.' },
      ] },
    { kind: 'p', text: 'The objective is not to move every process to Level 05.' },
    { kind: 'statement', text: 'The objective is to determine what level of autonomy is appropriate for this decision.' },

    { kind: 'h2', id: 'autonomous-enterprise', text: 'The Autonomous Enterprise' },
    { kind: 'p', text: 'An autonomous enterprise is not an organisation run entirely by machines.' },
    { kind: 'p', text: 'It is an organisation where intelligence can increasingly participate in operations.' },
    { kind: 'p', text: 'The architecture can be represented as:' },
    { kind: 'flow', steps: ['Sense', 'Understand', 'Think', 'Simulate', 'Coordinate', 'Act', 'Adapt'] },
    { kind: 'p', text: 'This can reduce the distance between:' },
    { kind: 'flow', steps: ['Signal', 'Understanding', 'Decision', 'Action'] },

    { kind: 'h2', id: 'use-cases', text: 'Enterprise Use Cases' },
    { kind: 'h3', id: 'intelligent-manufacturing', text: 'Intelligent Manufacturing' },
    { kind: 'p', text: 'Vision AI and sensors detect operational events. Edge AI processes information locally. Digital twins provide context. Simulation explores possible responses. AI agents coordinate workflows.' },
    { kind: 'h3', id: 'intelligent-infrastructure', text: 'Intelligent Infrastructure' },
    { kind: 'p', text: 'Connected systems monitor:' },
    { kind: 'ul', items: ['assets;', 'buildings;', 'utilities;', 'transportation;', 'environmental conditions.'] },
    { kind: 'p', text: 'Autonomous intelligence can help identify, understand and prioritise operational events.' },
    { kind: 'h3', id: 'autonomous-customer-operations', text: 'Autonomous Customer Operations' },
    { kind: 'p', text: 'An AI system may:' },
    { kind: 'ul', items: [
      'understand a customer request;', 'retrieve relevant context;',
      'investigate across multiple systems;', 'determine possible resolutions;',
      'execute approved actions;', 'escalate complex cases.',
    ] },
    { kind: 'h3', id: 'intelligent-supply-chains', text: 'Intelligent Supply Chains' },
    { kind: 'p', text: 'Autonomous systems can help evaluate:' },
    { kind: 'ul', items: ['demand changes;', 'supplier disruption;', 'inventory constraints;', 'transportation issues.'] },
    { kind: 'p', text: 'The objective moves beyond simply identifying disruption. The system can begin evaluating: what should happen next?' },
    { kind: 'h3', id: 'engineering-and-operations', text: 'Engineering and Operations' },
    { kind: 'p', text: 'Engineering organisations can connect:' },
    { kind: 'ul', items: ['operational data;', 'simulations;', 'design information;', 'AI reasoning;', 'automated workflows.'] },
    { kind: 'p', text: 'This can create more adaptive engineering environments.' },

    { kind: 'h2', id: 'maturity-model', text: 'The Autonomous Intelligence Maturity Model' },
    { kind: 'scale',
      caption: 'The autonomous intelligence maturity model',
      levels: [
        { label: 'Stage 01 — Digital', text: 'Information exists in digital systems. Fragmented software, manual processes, isolated data.' },
        { label: 'Stage 02 — Connected', text: 'Systems begin sharing information. Integrations, centralised data, connected workflows.' },
        { label: 'Stage 03 — Intelligent', text: 'AI begins analysing and interpreting information. Predictive models, AI assistants, anomaly detection.' },
        { label: 'Stage 04 — Agentic', text: 'AI systems can pursue defined objectives. AI agents, tool use, dynamic workflows.' },
        { label: 'Stage 05 — Autonomous', text: 'Intelligence participates in continuous operational loops: perception, context, reasoning, simulation, agency, governed action and adaptation.' },
      ] },

    { kind: 'h2', id: 'governance', text: 'Governance, Risk and Trust' },
    { kind: 'p', text: 'As systems gain the ability to act, governance becomes part of the architecture.' },
    { kind: 'p', text: 'Every autonomous intelligence system should define:' },
    { kind: 'defs', items: [
      { term: 'Objectives', text: 'What is the system trying to achieve?' },
      { term: 'Permissions', text: 'What systems can it access?' },
      { term: 'Action Boundaries', text: 'What is it allowed to do?' },
      { term: 'Escalation Rules', text: 'When must it involve a human?' },
      { term: 'Observability', text: 'Can actions and decisions be monitored?' },
      { term: 'Accountability', text: 'Who is responsible for the system?' },
    ] },
    { kind: 'p', text: 'Trust should not depend solely on the intelligence of a model. It should be designed into the system architecture.' },
    { kind: 'statement', text: 'The future of autonomous AI will depend as much on control as capability.' },

    { kind: 'h2', id: 'roadmap', text: 'A Practical Roadmap' },
    { kind: 'p', text: 'Organisations should not begin with: “How do we make everything autonomous?”' },
    { kind: 'p', text: 'A better question is: where is there a meaningful intelligence loop that can be improved?' },
    { kind: 'ol', items: [
      'Identify the environment. What process, system or operation needs greater intelligence?',
      'Map the signals. What information is available?',
      'Define the decision. What decision needs to improve?',
      'Design the context. What information must the system understand?',
      'Introduce intelligence. Where can AI add value?',
      'Define the action. What should happen after the decision?',
      'Establish governance. What actions are allowed?',
      'Create feedback. How will outcomes be measured?',
    ] },
    { kind: 'statement', text: 'Start with one intelligence loop. Prove value. Expand from there.' },

    { kind: 'h2', id: 'future', text: 'The Future of Intelligent Organisations' },
    { kind: 'p', text: 'The future organisation may increasingly interact with technology through objectives.' },
    { kind: 'p', text: 'Instead of navigating multiple applications, a person may ask:' },
    { kind: 'ul', items: [
      'What is happening across the organisation?', 'Why is this happening?',
      'What are the possible responses?', 'What do you recommend?', 'Execute the approved option.',
    ] },
    { kind: 'p', text: 'Behind that interaction may exist an entire ecosystem of AI models, agents, data systems, digital twins, simulations and enterprise applications.' },
    { kind: 'p', text: 'The interface becomes simpler. The underlying intelligence becomes more sophisticated.' },
    { kind: 'statement', text: 'As technology becomes more complex, the experience of using it should become simpler.' },
  ],

  closing: {
    heading: 'Closing Perspective',
    paragraphs: [
      'The next evolution of AI is not simply about producing better text, images or predictions.',
      'It is about connecting intelligence with the environments where real decisions happen.',
      'The emerging architecture connects perception with context, context with reasoning, reasoning with simulation, simulation with agency, agency with action, and action with feedback.',
      'This is the foundation of autonomous intelligence.',
      'The organisations that successfully build these systems will not necessarily be those with the most AI tools. They may be those that best connect intelligence across the entire operational loop.',
      'The future is not software that simply waits for instructions.',
      'It is intelligence that can understand the environment, reason about possibility and participate in what happens next.',
    ],
  },

  cta: {
    headline: 'PERCEIVE REALITY. UNDERSTAND CONTEXT. SIMULATE POSSIBILITY. COORDINATE INTELLIGENCE. ACT WITH PURPOSE.',
    body: 'The Autonomous Intelligence Imperative. Explore the technologies and architecture behind connected, governed autonomous systems.',
    links: [
      { label: 'Explore Deep Tech & Autonomous Intelligence', to: '/divisions/autonomous-intelligence' },
      { label: 'Explore AI OS', to: '/products/ai-os' },
      { label: 'Explore the SVARA Ecosystem', to: '/ecosystem' },
      { label: 'Talk to SVARA', to: '/contact' },
    ],
  },

  related: [
    { label: 'Deep Tech & Autonomous Intelligence', to: '/divisions/autonomous-intelligence' },
    { label: 'AI OS', to: '/products/ai-os' },
    { label: 'AI Agents', to: '/products/ai-agents' },
    { label: 'Vision AI', to: '/products/vision-ai' },
    { label: 'Edge AI', to: '/products/edge-ai' },
    { label: 'Digital Twin', to: '/products/digital-twin' },
  ],
}
