// INSIGHT 03 — "Edge AI vs Cloud AI"
//
// Comparison/cluster article under the Deep Tech & Autonomous Intelligence pillar. Copy is
// VERBATIM from the approved draft.
//
// Two things in here are deliberate and should survive editing:
//  · The piece repeatedly refuses to name a winner ("neither approach is universally
//    better", "there is no universal answer"). That even-handedness is the argument, not
//    hedging to be tidied away — the conclusion is hybrid.
//  · The privacy claim is scoped: local processing "can reduce the need to transmit raw
//    data", NOT "is more private". Edge AI is widely oversold on privacy, and the FAQ
//    answers that question honestly rather than marketing it.
import type { Insight } from './types'

export const edgeAiVsCloudAi: Insight = {
  slug: 'edge-ai-vs-cloud-ai',
  title: 'Edge AI vs Cloud AI',
  subtitle: 'Where Should Intelligence Actually Run?',
  seoTitle: 'Edge AI vs Cloud AI: Key Differences, Benefits and Use Cases',
  metaDescription:
    'Edge AI and Cloud AI process intelligence in different locations. Compare latency, privacy, scalability, cost and real-world use cases to understand the right AI architecture.',
  category: 'Deep Tech & Autonomous Intelligence',
  contentType: 'Comparison / Cluster Article',
  searchIntent: 'Informational + Commercial Investigation',
  readingTime: '10–12 minutes',
  published: '2026-09-02',
  primaryKeywords: [
    'edge AI vs cloud AI', 'edge AI', 'cloud AI', 'edge computing AI', 'edge AI architecture',
  ],
  secondaryKeywords: [
    'edge intelligence', 'cloud computing', 'real-time AI', 'AI inference at the edge',
    'hybrid AI architecture', 'on-device AI', 'low-latency AI', 'distributed AI systems',
  ],
  dek: 'The question is no longer which AI model to use, but where intelligence should run — and for most real systems the answer is not one or the other, but an architecture that is intelligently distributed.',
  heroImage: {
    name: 'edge-ai-vs-cloud-ai',
    alt:
      'A split comparison of Edge AI and Cloud AI. Edge AI, shown with cameras and robotics at street level, is labelled low latency, data privacy, offline capable, lower bandwidth and device optimised. Cloud AI, shown as a data centre in a cloud, is labelled high scalability, global accessibility, centralised data, high performance and rapid deployment. A comparison table below contrasts both against a hybrid approach.',
  },

  blocks: [
    { kind: 'h2', id: 'whats-the-difference', text: 'Edge AI vs Cloud AI: What’s the Difference?' },
    { kind: 'p', text: 'Artificial intelligence needs computing infrastructure.' },
    { kind: 'p', text: 'A model must run somewhere.' },
    { kind: 'p', text: 'The question is increasingly not just:' },
    { kind: 'p', text: 'What AI model should we use?' },
    { kind: 'p', text: 'It is also:' },
    { kind: 'statement', text: 'Where should intelligence run?' },
    { kind: 'p', text: 'Should data travel from a device to a central cloud environment for processing?' },
    { kind: 'p', text: 'Or should AI run closer to where the data is generated?' },
    { kind: 'p', text: 'This is the fundamental difference between Cloud AI and Edge AI.' },
    { kind: 'p', text: 'Cloud AI processes data primarily in centralised cloud infrastructure.' },
    { kind: 'p', text: 'Edge AI processes data on or near the device, machine or location where the data is generated.' },
    { kind: 'p', text: 'Neither approach is universally better.' },
    { kind: 'p', text: 'The right architecture depends on factors including:' },
    { kind: 'ul', items: [
      'latency requirements;', 'connectivity;', 'data sensitivity;', 'processing requirements;',
      'scalability;', 'operational environment;', 'infrastructure cost;', 'reliability requirements.',
    ] },
    { kind: 'p', text: 'For many real-world systems, the answer is not Edge AI versus Cloud AI.' },
    { kind: 'p', text: 'It is a combination of both.' },
    { kind: 'statement', text: 'The future of intelligent systems is increasingly distributed.' },

    { kind: 'h2', id: 'what-is-edge-ai', text: 'What Is Edge AI?' },
    { kind: 'p', text: 'Edge AI refers to artificial intelligence systems that process data and perform inference on or near the device where that data is generated.' },
    { kind: 'p', text: 'Instead of continuously sending raw information to a distant cloud server, the system can analyse information locally or within a nearby computing environment.' },
    { kind: 'p', text: 'A simplified architecture looks like:' },
    { kind: 'flow', steps: ['Sensor or Device', 'Edge Compute', 'AI Model', 'Decision or Action'] },
    { kind: 'p', text: 'For example:' },
    { kind: 'p', text: 'A camera observes an industrial environment.' },
    { kind: 'p', text: 'Instead of uploading every frame for remote analysis, an AI model running on an edge device can analyse the video locally.' },
    { kind: 'p', text: 'If an important event is detected, the system can then:' },
    { kind: 'ul', items: ['trigger an alert;', 'initiate an approved action;', 'store the event;', 'send relevant information to the cloud.'] },
    { kind: 'p', text: 'The edge becomes the point where data can become intelligence closer to the physical world.' },

    { kind: 'h2', id: 'what-is-cloud-ai', text: 'What Is Cloud AI?' },
    { kind: 'p', text: 'Cloud AI refers to AI workloads that run primarily within centralised cloud computing infrastructure.' },
    { kind: 'p', text: 'Data is transmitted from devices, applications or enterprise systems to cloud environments where models and computing resources process the information.' },
    { kind: 'p', text: 'A simplified architecture looks like:' },
    { kind: 'flow', steps: ['Device or Application', 'Network', 'Cloud Infrastructure', 'AI Processing', 'Result'] },
    { kind: 'p', text: 'Cloud AI can provide access to:' },
    { kind: 'ul', items: [
      'large-scale computing resources;', 'centralised data;', 'powerful AI models;',
      'scalable infrastructure;', 'model training environments;', 'enterprise-wide integrations.',
    ] },
    { kind: 'p', text: 'Cloud infrastructure can be particularly valuable when AI workloads require significant computational resources or need access to large, centralised datasets.' },

    { kind: 'h2', id: 'core-comparison', text: 'Edge AI vs Cloud AI: The Core Comparison' },
    { kind: 'table',
      caption: 'Edge AI and Cloud AI compared across nine factors',
      headers: ['Factor', 'Edge AI', 'Cloud AI'],
      rows: [
        ['Processing location', 'On or near the data source', 'Centralised cloud infrastructure'],
        ['Latency', 'Potentially very low', 'Depends on network and infrastructure'],
        ['Connectivity dependence', 'Can continue operating with limited connectivity', 'Often more dependent on network access'],
        ['Data transfer', 'Can reduce transmission of raw data', 'Often requires moving data to the cloud'],
        ['Scalability', 'Requires distributed infrastructure management', 'Highly scalable centrally'],
        ['Compute capacity', 'Limited by edge hardware', 'Can access significant compute resources'],
        ['Real-time response', 'Strong potential for time-sensitive applications', 'Can be limited by network delay'],
        ['Model training', 'More constrained', 'Well suited for large-scale training'],
        ['Deployment environment', 'Physical, distributed, operational', 'Centralised, digital and enterprise environments'],
      ] },
    { kind: 'p', text: 'The important point is that these are not rigid categories.' },
    { kind: 'p', text: 'Modern AI architectures can distribute workloads across devices, edge infrastructure and cloud environments.' },

    { kind: 'h2', id: 'latency', text: 'The Latency Question' },
    { kind: 'p', text: 'Latency is one of the most important reasons organisations consider Edge AI.' },
    { kind: 'p', text: 'Latency refers to the time between:' },
    { kind: 'ul', items: ['something happening;', 'the system receiving the data;', 'processing that information;', 'generating a response.'] },
    { kind: 'p', text: 'Imagine a computer vision system monitoring an industrial process.' },
    { kind: 'p', text: 'A cloud-based architecture may involve:' },
    { kind: 'flow', steps: ['Camera', 'Network', 'Cloud', 'AI Analysis', 'Network', 'Response'] },
    { kind: 'p', text: 'Every connection introduces potential delay.' },
    { kind: 'p', text: 'With Edge AI, the architecture may become:' },
    { kind: 'flow', steps: ['Camera', 'Local AI Processing', 'Response'] },
    { kind: 'p', text: 'For applications that require rapid responses, reducing the distance between data and intelligence can be significant.' },
    { kind: 'p', text: 'Potential use cases include:' },
    { kind: 'ul', items: [
      'industrial monitoring;', 'robotics;', 'autonomous systems;', 'machine vision;',
      'connected vehicles;', 'drone intelligence;', 'real-time safety applications.',
    ] },
    { kind: 'p', text: 'However, low latency is not required for every AI application.' },
    { kind: 'p', text: 'A system analysing a weekly business report has very different requirements from a system responding to events in milliseconds or seconds.' },
    { kind: 'p', text: 'The architecture should follow the operational need.' },

    { kind: 'h2', id: 'edge-and-computer-vision', text: 'Edge AI and Computer Vision' },
    { kind: 'p', text: 'Computer vision is one of the strongest examples of why Edge AI is becoming increasingly important.' },
    { kind: 'p', text: 'Video generates significant volumes of data.' },
    { kind: 'p', text: 'A single camera may produce a continuous stream of visual information.' },
    { kind: 'p', text: 'An environment containing hundreds or thousands of cameras can generate enormous amounts of data.' },
    { kind: 'p', text: 'Sending every frame to a central cloud environment may not always be the most efficient architecture.' },
    { kind: 'p', text: 'Edge AI allows intelligence to move closer to the camera.' },
    { kind: 'p', text: 'For example:' },
    { kind: 'flow', steps: ['Camera captures visual data', 'Edge device processes the video', 'AI identifies an event', 'Only the relevant event, metadata or selected footage is transmitted'] },
    { kind: 'p', text: 'This creates a more selective intelligence pipeline.' },
    { kind: 'p', text: 'Instead of:' },
    { kind: 'p', text: 'Send everything → analyse later.' },
    { kind: 'p', text: 'The architecture can become:' },
    { kind: 'statement', text: 'Analyse locally → identify relevance → transmit what matters.' },
    { kind: 'p', text: 'This approach can potentially improve responsiveness and reduce unnecessary data movement.' },

    { kind: 'h2', id: 'when-cloud-is-better', text: 'When Is Cloud AI the Better Choice?' },
    { kind: 'p', text: 'Edge AI is not a replacement for the cloud.' },
    { kind: 'p', text: 'Cloud infrastructure remains essential for many AI workloads.' },
    { kind: 'h3', id: 'large-scale-model-training', text: 'Large-Scale Model Training' },
    { kind: 'p', text: 'Training advanced AI models can require significant computational resources.' },
    { kind: 'p', text: 'Cloud infrastructure can provide scalable access to:' },
    { kind: 'ul', items: ['GPUs;', 'distributed computing;', 'storage;', 'machine learning platforms.'] },
    { kind: 'h3', id: 'enterprise-wide-intelligence', text: 'Enterprise-Wide Intelligence' },
    { kind: 'p', text: 'Large organisations often have data distributed across multiple systems.' },
    { kind: 'p', text: 'Cloud environments can help centralise or connect information across:' },
    { kind: 'ul', items: ['applications;', 'business units;', 'geographic locations;', 'databases;', 'analytics platforms.'] },
    { kind: 'h3', id: 'large-ai-models', text: 'Large AI Models' },
    { kind: 'p', text: 'Some advanced models require more memory and computational capacity than a typical edge device can provide.' },
    { kind: 'p', text: 'Cloud infrastructure can support these larger workloads.' },
    { kind: 'h3', id: 'centralised-model-management', text: 'Centralised Model Management' },
    { kind: 'p', text: 'Organisations may need to manage:' },
    { kind: 'ul', items: ['model versions;', 'updates;', 'monitoring;', 'testing;', 'security;', 'deployment.'] },
    { kind: 'p', text: 'Cloud platforms can provide a central layer for managing distributed AI systems.' },

    { kind: 'h2', id: 'when-edge-is-better', text: 'When Is Edge AI the Better Choice?' },
    { kind: 'p', text: 'Edge AI can become particularly valuable when intelligence needs to operate closer to the source of information.' },
    { kind: 'h3', id: 'real-time-environments', text: 'Real-Time Environments' },
    { kind: 'p', text: 'Applications requiring fast responses may benefit from local processing.' },
    { kind: 'p', text: 'Examples include:' },
    { kind: 'ul', items: ['industrial automation;', 'robotics;', 'computer vision;', 'autonomous machines.'] },
    { kind: 'h3', id: 'limited-connectivity', text: 'Limited Connectivity' },
    { kind: 'p', text: 'Some environments may have:' },
    { kind: 'ul', items: ['unreliable networks;', 'intermittent connectivity;', 'remote locations;', 'restricted communication infrastructure.'] },
    { kind: 'p', text: 'Edge AI can enable certain intelligence capabilities to continue functioning even when a continuous cloud connection is unavailable.' },
    { kind: 'h3', id: 'high-volume-sensor-data', text: 'High-Volume Sensor Data' },
    { kind: 'p', text: 'Transmitting every piece of sensor or video data can create significant infrastructure requirements.' },
    { kind: 'p', text: 'Processing information locally can allow systems to filter, summarise or prioritise data before transmission.' },
    { kind: 'h3', id: 'data-locality', text: 'Data Locality Requirements' },
    { kind: 'p', text: 'Some applications may benefit from processing information closer to where it is generated.' },
    { kind: 'p', text: 'The specific privacy, security and compliance requirements will depend on the organisation, industry and jurisdiction.' },

    { kind: 'h2', id: 'hybrid-architectures', text: 'The Rise of Hybrid AI Architectures' },
    { kind: 'p', text: 'The most powerful AI architecture is often not completely edge-based or completely cloud-based.' },
    { kind: 'p', text: 'It is hybrid.' },
    { kind: 'p', text: 'A hybrid architecture can distribute intelligence based on what each environment does best.' },
    { kind: 'p', text: 'For example:' },
    { kind: 'defs', items: [
      { term: 'The Edge', text: 'Handles real-time data processing, local inference, immediate responses and device intelligence.' },
      { term: 'The Cloud', text: 'Handles large-scale model training, centralised analytics, cross-system intelligence, long-term storage and model management.' },
    ] },
    { kind: 'p', text: 'The architecture becomes:' },
    { kind: 'stack', layers: [
      { name: 'Physical World', items: ['Sensors', 'Cameras', 'Devices', 'Machines'] },
      { name: 'Edge Intelligence', items: ['Real-time perception', 'Local inference', 'Immediate action'] },
      { name: 'Cloud Intelligence', items: ['Large-scale analysis', 'Model management', 'Enterprise coordination'] },
      { name: 'AI Orchestration', items: ['Agents', 'Workflows', 'Decisions', 'Human oversight'] },
    ] },
    { kind: 'p', text: 'This is not simply infrastructure design.' },
    { kind: 'statement', text: 'It is intelligence architecture.' },

    { kind: 'h2', id: 'edge-and-autonomous-systems', text: 'Edge AI and Autonomous Systems' },
    { kind: 'p', text: 'Autonomous systems need to operate in environments that can change quickly.' },
    { kind: 'p', text: 'A system may need to:' },
    { kind: 'ul', items: ['observe;', 'interpret;', 'decide;', 'act.'] },
    { kind: 'p', text: 'If every decision depends on transmitting information to a distant computing environment, responsiveness can be affected by network conditions.' },
    { kind: 'p', text: 'Edge AI can provide a local intelligence layer.' },
    { kind: 'p', text: 'For example, an autonomous drone could potentially process information from cameras and sensors closer to the point of operation.' },
    { kind: 'p', text: 'A simplified flow might be:' },
    { kind: 'flow', steps: ['Sensors', 'Edge AI', 'Environmental Understanding', 'Decision', 'Action'] },
    { kind: 'p', text: 'Relevant data can still be transmitted to central systems for:' },
    { kind: 'ul', items: ['fleet management;', 'analytics;', 'reporting;', 'model improvement;', 'long-term intelligence.'] },
    { kind: 'p', text: 'This illustrates why distributed AI is becoming increasingly important.' },
    { kind: 'p', text: 'The physical world generates information everywhere.' },
    { kind: 'statement', text: 'Intelligence may need to operate everywhere too.' },

    { kind: 'h2', id: 'edge-agents-connected', text: 'Edge AI, AI Agents and Connected Intelligence' },
    { kind: 'p', text: 'Edge AI can also become part of a larger network of intelligent systems.' },
    { kind: 'p', text: 'Imagine a computer vision system detecting an anomaly.' },
    { kind: 'p', text: 'The edge system performs the initial analysis.' },
    { kind: 'p', text: 'It identifies the event as potentially significant.' },
    { kind: 'p', text: 'That event is then passed to an AI agent.' },
    { kind: 'p', text: 'The agent can:' },
    { kind: 'ul', items: [
      'retrieve relevant operational information;', 'analyse historical events;', 'check maintenance records;',
      'identify potential actions;', 'notify the appropriate team;', 'initiate an approved workflow.',
    ] },
    { kind: 'p', text: 'The architecture becomes:' },
    { kind: 'stack', layers: [
      { name: 'Perception', items: ['Vision AI', 'Sensors', 'Devices'] },
      { name: 'Local Intelligence', items: ['Edge AI'] },
      { name: 'Contextual Intelligence', items: ['Cloud AI', 'Enterprise Data', 'Knowledge Systems'] },
      { name: 'Agency', items: ['AI Agents', 'Workflow Systems'] },
      { name: 'Action', items: ['People', 'Software', 'Machines'] },
    ] },
    { kind: 'p', text: 'This is the direction beyond isolated AI deployments.' },
    { kind: 'p', text: 'Different forms of intelligence can operate at different layers of the system.' },

    { kind: 'h2', id: 'cost', text: 'Edge AI vs Cloud AI: Cost Considerations' },
    { kind: 'p', text: 'Cost should not be evaluated based only on the price of an edge device or cloud service.' },
    { kind: 'p', text: 'The full architecture matters.' },
    { kind: 'p', text: 'Cloud-based systems may involve costs associated with:' },
    { kind: 'ul', items: ['computing;', 'storage;', 'data transfer;', 'infrastructure scaling.'] },
    { kind: 'p', text: 'Edge AI may introduce costs related to:' },
    { kind: 'ul', items: ['specialised hardware;', 'distributed deployment;', 'maintenance;', 'monitoring;', 'device management.'] },
    { kind: 'p', text: 'The question should therefore be:' },
    { kind: 'statement', text: 'What is the total operational cost of the intelligence architecture?' },
    { kind: 'p', text: 'For a high-volume vision system, transmitting and processing every frame centrally may have different economics than analysing information locally and transmitting only relevant events.' },
    { kind: 'p', text: 'For a large language model serving a global enterprise, centralised cloud infrastructure may provide greater efficiency.' },
    { kind: 'p', text: 'There is no universal answer.' },
    { kind: 'p', text: 'The use case determines the architecture.' },

    { kind: 'h2', id: 'security-and-governance', text: 'Security and Governance in Distributed AI' },
    { kind: 'p', text: 'As intelligence becomes distributed, governance becomes more complex.' },
    { kind: 'p', text: 'An organisation may have AI operating across:' },
    { kind: 'ul', items: ['cloud infrastructure;', 'edge devices;', 'enterprise applications;', 'AI agents;', 'connected machines.'] },
    { kind: 'p', text: 'Important questions include:' },
    { kind: 'ul', items: [
      'Which systems can access which data?', 'Which AI models can take action?',
      'What actions require approval?', 'How are decisions logged?', 'How are models updated?',
      'What happens if connectivity is lost?', 'How is device identity managed?',
    ] },
    { kind: 'statement', text: 'Autonomy without governance can create risk.' },
    { kind: 'p', text: 'A mature architecture should therefore consider identity, permissions, observability and human oversight as part of the AI system itself.' },

    { kind: 'h2', id: 'how-to-choose', text: 'How Should Organisations Choose?' },
    { kind: 'p', text: 'A useful framework is to evaluate the AI use case across five questions.' },
    { kind: 'h3', id: 'q1-speed', text: '1. How Fast Does the System Need to Respond?' },
    { kind: 'p', text: 'If a delay of several seconds or minutes is acceptable, cloud processing may be sufficient.' },
    { kind: 'p', text: 'If the application requires near-immediate processing, Edge AI may be more appropriate.' },
    { kind: 'h3', id: 'q2-data-volume', text: '2. How Much Data Is Being Generated?' },
    { kind: 'p', text: 'High-volume video and sensor environments may benefit from processing closer to the source.' },
    { kind: 'h3', id: 'q3-connectivity', text: '3. How Reliable Is Connectivity?' },
    { kind: 'p', text: 'If a system operates in remote or intermittently connected environments, local intelligence may be important.' },
    { kind: 'h3', id: 'q4-compute', text: '4. How Much Computing Power Is Required?' },
    { kind: 'p', text: 'Large models and intensive workloads may require cloud-scale infrastructure.' },
    { kind: 'h3', id: 'q5-where-to-act', text: '5. Where Does the Intelligence Need to Act?' },
    { kind: 'p', text: 'This may be the most important question.' },
    { kind: 'p', text: 'If intelligence needs to act in the physical world, it may need to operate closer to the physical world.' },
    { kind: 'p', text: 'If intelligence coordinates enterprise-wide information, the cloud may provide a more suitable environment.' },
    { kind: 'p', text: 'If both are required, a hybrid architecture may be the answer.' },

    { kind: 'h2', id: 'svara-perspective', text: 'The SVARA Perspective: Intelligence Should Run Where It Creates the Most Value' },
    { kind: 'p', text: 'The conversation should not be:' },
    { kind: 'p', text: 'Edge AI or Cloud AI?' },
    { kind: 'p', text: 'It should be:' },
    { kind: 'statement', text: 'Where should each part of the intelligence system operate?' },
    { kind: 'p', text: 'A modern intelligent architecture may distribute capabilities across multiple environments.' },
    { kind: 'defs', items: [
      { term: 'Vision AI', text: 'can observe the physical world.' },
      { term: 'Edge AI', text: 'can process information close to the source.' },
      { term: 'Cloud intelligence', text: 'can provide large-scale analysis and coordination.' },
      { term: 'AI Agents', text: 'can execute multi-step workflows.' },
      { term: 'Digital Twins and Simulation', text: 'can model systems and possible outcomes.' },
      { term: 'AI OS', text: 'can help orchestrate intelligence across the ecosystem.' },
    ] },
    { kind: 'p', text: 'The result is not a single AI location.' },
    { kind: 'p', text: 'It is a distributed intelligence architecture.' },
    { kind: 'statement', text: 'The future of AI is not centralised or decentralised. It is intelligently distributed.' },
  ],

  faqs: [
    { q: 'What is the difference between Edge AI and Cloud AI?', a: 'Edge AI processes AI workloads on or near the device where data is generated. Cloud AI processes workloads primarily in centralised cloud infrastructure.' },
    { q: 'Is Edge AI faster than Cloud AI?', a: 'Edge AI can reduce latency by processing data closer to the source. Actual performance depends on hardware, software, network architecture and the specific AI workload.' },
    { q: 'Can Edge AI work without the internet?', a: 'Some Edge AI systems can continue performing local inference without continuous internet connectivity. However, certain features such as cloud synchronisation, remote monitoring or model updates may still require connectivity.' },
    { q: 'Is Edge AI more private?', a: 'Processing data locally can reduce the need to transmit raw data to remote infrastructure. However, privacy and security depend on the complete system architecture, access controls and how information is managed.' },
    { q: 'Can Edge AI and Cloud AI work together?', a: 'Yes. Hybrid architectures can use Edge AI for local and real-time processing while using cloud infrastructure for large-scale analytics, training, storage and centralised management.' },
    { q: 'What industries use Edge AI?', a: 'Edge AI can be applied in manufacturing, logistics, robotics, transportation, infrastructure, drones, smart environments and other applications requiring local or real-time intelligence.' },
  ],

  closing: {
    heading: 'Closing Perspective',
    paragraphs: [
      'AI is leaving the screen.',
      'It is moving into cameras, machines, vehicles, drones, factories, infrastructure and connected environments.',
      'As AI enters the physical world, intelligence cannot always remain in one distant location.',
      'Some decisions need to happen immediately.',
      'Some data needs to be analysed locally.',
      'Some intelligence needs access to the scale of the cloud.',
      'The answer is not choosing one environment over another.',
      'It is designing an architecture where every layer performs the role it is best suited to perform.',
      'Edge AI brings intelligence closer to reality.',
      'Cloud AI brings intelligence to scale.',
      'Together, they can form the foundation of connected autonomous intelligence.',
    ],
  },

  cta: {
    headline: 'PUT INTELLIGENCE WHERE IT MATTERS.',
    body: 'From real-time Edge AI and Vision AI to AI Agents, Digital Twins and intelligent orchestration, SVARA is building toward a future where intelligence can operate across the physical and digital world.',
    links: [
      { label: 'Explore Edge AI', to: '/products/edge-ai' },
      { label: 'Explore Vision AI', to: '/products/vision-ai' },
      { label: 'Explore Autonomous Intelligence', to: '/divisions/autonomous-intelligence' },
      { label: 'Explore the SVARA Ecosystem', to: '/ecosystem' },
    ],
  },

  related: [
    { label: 'Deep Tech & Autonomous Intelligence', to: '/divisions/autonomous-intelligence' },
    { label: 'Edge AI', to: '/products/edge-ai' },
    { label: 'Vision AI', to: '/products/vision-ai' },
    { label: 'Drone AI', to: '/products/drone-ai' },
    { label: 'AI Agents', to: '/products/ai-agents' },
    { label: 'Digital Twin', to: '/products/digital-twin' },
    { label: 'AI OS', to: '/products/ai-os' },
  ],
}
