// WHITE PAPER 04 — "Product Engineering: From Vision AI to Autonomous Agents"
//
// kind: 'paper', design: 'report' — the house treatment. Copy is VERBATIM from the
// approved draft.
//
// This paper names TEN SVARA products and describes how each composes with the others.
// Every product name here must keep matching lib/content/routes.ts and the product pages:
// a white paper that describes a product the site does not have is the fastest way to
// lose a reader's trust in the rest of it.
import type { Insight } from './types'

export const productEngineering: Insight = {
  slug: 'product-engineering',
  kind: 'paper',
  design: 'report',
  title: 'Product Engineering',
  subtitle: 'From Vision AI to Autonomous Agents — how SVARA products compose into one intelligence stack, from edge perception to enterprise-wide automation.',
  seoTitle: 'Product Engineering: From Vision AI to Autonomous Agents — SVARA White Paper',
  metaDescription:
    'How SVARA products compose into one intelligence stack. A product architecture white paper covering perception, context, reasoning, simulation, agency, orchestration and enterprise execution.',
  category: 'Product Engineering · Autonomous Intelligence · AI Systems',
  contentType: 'White Paper',
  searchIntent: 'Informational',
  readingTime: '30–40 minutes',
  extent: '30–40 pages',
  published: '2026-09-02',
  primaryKeywords: [
    'AI product architecture', 'composable AI stack', 'AI product engineering',
    'vision AI to autonomous agents', 'enterprise AI stack',
  ],
  secondaryKeywords: [
    'Vision AI', 'Drone AI', 'Edge AI', 'digital twins', 'AI agents', 'AI OS',
    'business cloud', 'digital engineering', 'product interoperability',
  ],
  dek: 'Individual AI capabilities become significantly more valuable when they can compose into a connected operating stack. This is where product engineering becomes intelligence architecture.',

  corePosition: {
    heading: 'The Core Thesis',
    paragraphs: [
      'Most AI products are presented as isolated capabilities: a computer vision platform, an AI agent, a digital twin, an enterprise cloud, an orchestration system, an automation platform.',
      'But real intelligence does not operate in isolation. A camera can detect an event. That event requires context. Context requires data. Data may need reasoning. Reasoning may benefit from simulation. A decision may require specialised AI agents. Those agents require orchestration. And action must eventually connect back to enterprise systems.',
      'This is where product engineering becomes intelligence architecture.',
      'SVARA’s product ecosystem is designed around a larger idea: individual AI capabilities become significantly more valuable when they can compose into a connected operating stack.',
      'The result is not simply a collection of products. It is a composable intelligence architecture.',
    ],
  },

  blocks: [
    { kind: 'h2', id: 'executive-summary', text: 'Executive Summary' },
    { kind: 'p', text: 'Artificial intelligence is becoming increasingly modular. Organisations can now access powerful capabilities for:' },
    { kind: 'ul', items: [
      'visual perception;', 'language and multimodal reasoning;', 'prediction;',
      'simulation;', 'autonomous task execution;', 'workflow automation.',
    ] },
    { kind: 'p', text: 'But access to AI capabilities is not the same as having an intelligence architecture.' },
    { kind: 'statement', text: 'The challenge is composition.' },
    { kind: 'p', text: 'How does information move from one intelligence layer to another? How does a visual event become an enterprise decision? How does a prediction influence an action? How do multiple AI agents work together? How are permissions, context and workflows coordinated?' },
    { kind: 'p', text: 'SVARA approaches this challenge through a connected product architecture. The stack can be understood as a movement from reality to intelligence to action.' },
    { kind: 'stack', layers: [
      { name: 'Reality', items: ['The physical and digital environment'] },
      { name: 'Perception', items: ['Vision AI', 'Drone AI', 'Edge AI'] },
      { name: 'Intelligence', items: ['Generative AI', 'Cognitive AI'] },
      { name: 'Context', items: ['Digital Twins', 'Enterprise Knowledge', 'Data'] },
      { name: 'Agency', items: ['AI Agents'] },
      { name: 'Orchestration', items: ['One AI OS'] },
      { name: 'Enterprise Execution', items: ['Business Cloud', 'Enterprise Systems', 'Workflows'] },
      { name: 'Engineering', items: ['Digital Engineering'] },
      { name: 'Activation', items: ['Digital Growth'] },
      { name: 'Outcome', items: ['The resulting data becomes part of the next intelligence loop'] },
    ] },
    { kind: 'p', text: 'The architecture is composable. A customer does not necessarily need every product.' },
    { kind: 'p', text: 'Vision AI can operate independently. AI Agents can connect to existing enterprise systems. Digital Twins can become a contextual layer for specific environments. One AI OS can coordinate multiple intelligence capabilities.' },
    { kind: 'p', text: 'But when products are connected, they can form a larger intelligence loop.' },

    { kind: 'h2', id: 'standalone-problem', text: 'The Problem With Standalone AI Products' },
    { kind: 'p', text: 'AI adoption often begins with a specific problem. An organisation needs to inspect an environment, so it deploys computer vision. Another team needs automation, so it deploys an AI agent. Another needs forecasting, so it adopts a predictive model.' },
    { kind: 'p', text: 'Over time, the organisation may accumulate intelligence tools without creating a connected intelligence system. This can create several challenges.' },
    { kind: 'defs', items: [
      { term: 'Fragmented context', text: 'Different AI systems operate with incomplete information.' },
      { term: 'Disconnected decisions', text: 'Insights remain inside individual applications.' },
      { term: 'Limited action', text: 'AI may generate recommendations without connecting to execution.' },
      { term: 'Duplicated infrastructure', text: 'Teams independently build similar capabilities.' },
      { term: 'Governance complexity', text: 'Each new AI system introduces its own permissions and controls.' },
    ] },
    { kind: 'p', text: 'The challenge is no longer simply building individual AI products. It is designing how intelligence moves between them.' },
    { kind: 'statement', text: 'The next stage of product engineering is not only about what a product can do. It is about what it can connect to.' },

    { kind: 'h2', id: 'the-stack', text: 'Introducing the SVARA Product Stack' },
    { kind: 'p', text: 'The SVARA ecosystem can be viewed as a composable stack.' },
    { kind: 'defs', items: [
      { term: 'Vision AI — perception', text: 'Transforms visual environments into structured intelligence.' },
      { term: 'Drone AI — perception', text: 'Extends perception into mobile and large-scale environments.' },
      { term: 'Edge AI — perception', text: 'Moves intelligence closer to where data is generated.' },
      { term: 'Generative & Cognitive AI — intelligence', text: 'Interprets information, generates insight and supports reasoning.' },
      { term: 'Digital Twins — context and simulation', text: 'Creates connected representations of assets, processes and environments.' },
      { term: 'AI Agents — agency', text: 'Transforms intelligence into goal-oriented digital action.' },
      { term: 'One AI OS — orchestration', text: 'Coordinates models, agents, context, workflows and intelligence systems.' },
      { term: 'Business Cloud — enterprise', text: 'Connects intelligence with enterprise operations, applications and workflows.' },
      { term: 'Digital Engineering — build', text: 'Designs, integrates and develops the underlying digital infrastructure.' },
      { term: 'Digital Growth — activation', text: 'Extends intelligence into digital experiences, customer journeys and growth systems.' },
    ] },

    { kind: 'h2', id: 'product-engineering', text: 'Product Engineering as Intelligence Architecture' },
    { kind: 'p', text: 'Traditional product engineering often follows a relatively direct model:' },
    { kind: 'flow', steps: ['Problem', 'Feature', 'Application', 'User'] },
    { kind: 'p', text: 'AI product engineering introduces additional dimensions. The product must consider:' },
    { kind: 'ul', items: [
      'data;', 'context;', 'models;', 'reasoning;', 'actions;', 'integrations;',
      'feedback;', 'governance.',
    ] },
    { kind: 'p', text: 'The architecture becomes dynamic. A product may receive information from another product. It may enrich that information. It may trigger another intelligence capability. It may return the outcome back into the wider system.' },
    { kind: 'statement', text: 'The value of an intelligent product increasingly depends not only on its individual capability, but on its ability to participate in a larger intelligence loop.' },
    { kind: 'p', text: 'SVARA product engineering is therefore structured around composition. Each product can represent a capability. Together, the capabilities can form an operating architecture.' },

    { kind: 'h2', id: 'vision-ai', text: 'Layer One: Vision AI — Perceiving the Environment' },
    { kind: 'p', text: 'Vision AI creates a bridge between visual reality and digital intelligence.' },
    { kind: 'p', text: 'The physical world contains enormous amounts of information: people, objects, movement, conditions, events and patterns. Traditionally, much of this information required human observation.' },
    { kind: 'p', text: 'Vision AI enables systems to extract structured signals from visual environments. The process can be represented as:' },
    { kind: 'flow', steps: ['Camera', 'Visual Input', 'Vision AI', 'Object / Event / Pattern', 'Structured Intelligence'] },
    { kind: 'p', text: 'That intelligence can then move into other SVARA capabilities. For example:' },
    { kind: 'flow', steps: ['Vision AI detects an event', 'Edge AI processes locally', 'Generative & Cognitive AI interprets', 'Digital Twin provides context', 'AI Agent coordinates the next action'] },
    { kind: 'p', text: 'Vision AI is therefore not simply an endpoint. It can become the first stage of a larger intelligence pipeline.' },

    { kind: 'h2', id: 'drone-ai', text: 'Layer Two: Drone AI — Extending Perception' },
    { kind: 'p', text: 'Some environments cannot be effectively observed from a fixed position. Infrastructure may extend across large areas. Industrial environments may be difficult or dangerous to inspect. Remote locations may require mobile perception.' },
    { kind: 'p', text: 'Drone AI extends the perception layer. The architecture can combine mobility, sensors, vision and edge intelligence.' },
    { kind: 'p', text: 'A drone can become a mobile intelligence node. It can capture environmental information, AI can analyse the data, and relevant signals can move into the wider intelligence stack. For example:' },
    { kind: 'flow', steps: ['Drone observation', 'Vision AI analysis', 'Edge processing', 'Digital Twin update', 'Anomaly identified', 'AI Agent coordination', 'Enterprise action'] },
    { kind: 'p', text: 'The drone is therefore more than a data collection device.' },
    { kind: 'statement', text: 'Within a connected architecture, it becomes part of the perception layer of an intelligent operating system.' },

    { kind: 'h2', id: 'edge-ai', text: 'Layer Three: Edge AI — Bringing Intelligence Closer to Reality' },
    { kind: 'p', text: 'Not every intelligence task should begin in the cloud. Some environments require rapid local interpretation.' },
    { kind: 'p', text: 'Edge AI processes selected intelligence workloads closer to where data is generated. This can create an architecture such as:' },
    { kind: 'flow', steps: ['Camera / Sensor / Device', 'Edge AI', 'Local Intelligence', 'Event Detection', 'Selective Data Transfer', 'Enterprise Intelligence'] },
    { kind: 'p', text: 'Edge AI can act as a filter. Instead of moving every raw signal through the entire enterprise architecture, it can identify meaningful events. The result can then be passed into:' },
    { kind: 'ul', items: ['Vision AI;', 'Generative & Cognitive AI;', 'Digital Twins;', 'AI Agents;', 'One AI OS.'] },
    { kind: 'statement', text: 'The edge observes and responds to reality. The wider intelligence stack coordinates what happens next.' },

    { kind: 'h2', id: 'generative-cognitive', text: 'Layer Four: Generative & Cognitive AI — Turning Information Into Intelligence' },
    { kind: 'p', text: 'Perception creates signals. But signals require interpretation.' },
    { kind: 'p', text: 'Generative and cognitive AI can support:' },
    { kind: 'ul', items: [
      'reasoning;', 'explanation;', 'synthesis;', 'knowledge retrieval;', 'planning;',
      'multimodal interpretation;', 'decision support.',
    ] },
    { kind: 'p', text: 'Within the SVARA stack, this layer receives information from multiple sources — a vision event, enterprise data, digital twin context and historical information — and begins evaluating:' },
    { kind: 'ul', items: [
      'What happened?', 'Why might it have happened?', 'What information is relevant?',
      'What should be investigated?', 'What are the possible responses?',
    ] },
    { kind: 'p', text: 'The intelligence layer does not need to operate alone. It can interact with simulation and AI agents. This creates a flow from:' },
    { kind: 'flow', steps: ['Perception', 'Understanding', 'Reasoning', 'Action'] },

    { kind: 'h2', id: 'digital-twins', text: 'Layer Five: Digital Twins — An Intelligence Model of the Environment' },
    { kind: 'p', text: 'Digital Twins can provide the context layer. An event rarely exists in isolation.' },
    { kind: 'p', text: 'Consider a visual anomaly. The system may need to understand:' },
    { kind: 'ul', items: [
      'Which asset is involved?', 'What systems are connected?', 'What is the current state?',
      'What happened previously?', 'What operational constraints exist?',
    ] },
    { kind: 'p', text: 'A digital twin can help structure this information. Within the SVARA stack:' },
    { kind: 'flow', steps: ['Reality', 'Perception', 'Digital Representation', 'Context', 'Simulation', 'Decision', 'Action', 'Updated Reality'] },
    { kind: 'p', text: 'Digital Twins can therefore connect perception with understanding and simulation. They help transform isolated signals into part of a larger operational model.' },

    { kind: 'h2', id: 'ai-agents', text: 'Layer Six: AI Agents — From Intelligence to Agency' },
    { kind: 'p', text: 'AI agents provide the capability to work toward defined objectives.' },
    { kind: 'p', text: 'Once the system has perceived an event, understood its meaning, retrieved context and reasoned about possibilities, an agent can coordinate the next stage.' },
    { kind: 'p', text: 'An AI agent may:' },
    { kind: 'ul', items: [
      'receive an objective;', 'retrieve information;', 'use authorised tools;', 'perform tasks;',
      'coordinate with other agents;', 'monitor progress;', 'escalate when required.',
    ] },
    { kind: 'p', text: 'A multi-agent system may include specialised capabilities.' },
    { kind: 'stack', layers: [
      { name: 'Investigation Agent', items: ['Determines what happened'] },
      { name: 'Context Agent', items: ['Retrieves relevant information'] },
      { name: 'Simulation Agent', items: ['Evaluates possible outcomes'] },
      { name: 'Execution Agent', items: ['Coordinates approved actions'] },
      { name: 'Observation Agent', items: ['Monitors the result'] },
    ] },
    { kind: 'p', text: 'The agents do not replace the rest of the stack. They connect intelligence with action.' },

    { kind: 'h2', id: 'ai-os', text: 'Layer Seven: One AI OS — Orchestrating the Intelligence Stack' },
    { kind: 'p', text: 'As the number of AI capabilities grows, coordination becomes critical.' },
    { kind: 'p', text: 'One AI OS represents the orchestration layer. Its purpose is to help coordinate:' },
    { kind: 'ul', items: [
      'intelligence models;', 'AI agents;', 'data;', 'context;', 'tools;',
      'workflows;', 'permissions;', 'human oversight.',
    ] },
    { kind: 'p', text: 'One AI OS can answer architectural questions such as: which AI capability should handle this event? What context should it receive? Which agents should participate? Which systems can they access? What actions require approval?' },
    { kind: 'p', text: 'The role of the AI OS is not necessarily to perform every task. It is to coordinate the system that performs them.' },
    { kind: 'statement', text: 'If AI models provide intelligence and agents provide agency, One AI OS provides orchestration.' },

    { kind: 'h2', id: 'business-cloud', text: 'Layer Eight: Business Cloud — Connecting Intelligence to the Enterprise' },
    { kind: 'p', text: 'Intelligence becomes operational when it can connect to business systems.' },
    { kind: 'p', text: 'Business Cloud provides the enterprise environment where information, workflows and operational activity can connect. This can include business processes, enterprise applications, data, workflows, users and automation.' },
    { kind: 'p', text: 'The flow may become:' },
    { kind: 'flow', steps: ['AI Event', 'One AI OS', 'AI Agent', 'Business Cloud', 'Workflow / Enterprise System', 'Outcome'] },
    { kind: 'p', text: 'The enterprise is no longer simply receiving AI recommendations. Intelligence can become connected to the operational environment.' },

    { kind: 'h2', id: 'engineering-growth', text: 'The Engineering and Growth Layer' },
    { kind: 'h3', id: 'digital-engineering', text: 'Digital Engineering' },
    { kind: 'p', text: 'Every intelligence architecture requires implementation. Digital Engineering supports the creation of:' },
    { kind: 'ul', items: [
      'applications;', 'platforms;', 'integrations;', 'APIs;', 'infrastructure;',
      'data systems;', 'user experiences.',
    ] },
    { kind: 'p', text: 'It is the build layer behind the intelligence stack. It ensures products can integrate with the real environments where customers operate.' },
    { kind: 'h3', id: 'digital-growth', text: 'Digital Growth' },
    { kind: 'p', text: 'Intelligence does not end inside enterprise operations. It can also influence how organisations interact with markets and customers.' },
    { kind: 'p', text: 'Digital Growth can connect customer intelligence, digital experiences, campaign systems, content, analytics and optimisation.' },
    { kind: 'p', text: 'The intelligence loop can therefore extend outward:' },
    { kind: 'flow', steps: ['Internal Intelligence', 'Customer Experience', 'Market Response', 'Back Again'] },

    { kind: 'h2', id: 'how-they-compose', text: 'How the Products Compose' },
    { kind: 'p', text: 'The strength of the SVARA ecosystem lies in composition. Here is an example — a scenario in which an event is detected.' },
    { kind: 'flow', steps: [
      'Vision AI detects an unusual event',
      'Edge AI validates it locally',
      'Generative & Cognitive AI interprets',
      'Digital Twin provides context',
      'Simulation evaluates outcomes',
      'AI Agents coordinate response',
      'One AI OS orchestrates',
      'Business Cloud connects to enterprise systems',
      'Digital Engineering provides infrastructure',
      'Digital Growth activates where relevant',
      'Feedback becomes new information',
    ] },
    { kind: 'statement', text: 'The loop continues.' },

    { kind: 'h2', id: 'end-to-end', text: 'The End-to-End Intelligence Flow' },
    { kind: 'p', text: 'The complete SVARA product flow can be represented as:' },
    { kind: 'stack', layers: [
      { name: 'Observe', items: ['Vision AI', 'Drone AI'] },
      { name: 'Process', items: ['Edge AI'] },
      { name: 'Understand', items: ['Generative & Cognitive AI'] },
      { name: 'Contextualise', items: ['Digital Twins'] },
      { name: 'Reason + Simulate', items: ['Intelligence Systems'] },
      { name: 'Coordinate', items: ['AI Agents'] },
      { name: 'Orchestrate', items: ['One AI OS'] },
      { name: 'Execute', items: ['Business Cloud'] },
      { name: 'Build + Integrate', items: ['Digital Engineering'] },
      { name: 'Activate + Optimise', items: ['Digital Growth'] },
      { name: 'Learn', items: ['Feedback', 'New Context', 'Next Intelligence Loop'] },
    ] },

    { kind: 'h2', id: 'reference-architecture', text: 'Reference Architecture' },
    { kind: 'p', text: 'A conceptual SVARA deployment can be structured into five architectural zones.' },
    { kind: 'stack', layers: [
      { name: 'Zone 01 — Reality', items: ['Cameras', 'Drones', 'Sensors', 'Enterprise systems', 'Customer interactions'] },
      { name: 'Zone 02 — Intelligence', items: ['Vision AI', 'Edge AI', 'Generative AI', 'Cognitive AI'] },
      { name: 'Zone 03 — Context', items: ['Digital Twins', 'Enterprise data', 'Knowledge', 'Historical information'] },
      { name: 'Zone 04 — Agency', items: ['AI Agents', 'Workflows', 'Automation', 'Human approvals'] },
      { name: 'Zone 05 — Orchestration', items: ['One AI OS', 'Business Cloud', 'Governance', 'Permissions', 'Observability'] },
    ] },
    { kind: 'p', text: 'Digital Engineering connects the architecture. Digital Growth extends intelligence into the market.' },

    { kind: 'h2', id: 'interoperability', text: 'Product Interoperability' },
    { kind: 'p', text: 'Composable products require interoperability. Each product should be capable of operating:' },
    { kind: 'defs', items: [
      { term: 'Independently', text: 'Solving a specific problem.' },
      { term: 'Connected', text: 'Sharing information with other SVARA products.' },
      { term: 'Extensible', text: 'Integrating with external systems.' },
    ] },
    { kind: 'p', text: 'This creates three deployment models.' },
    { kind: 'scale',
      caption: 'Deployment models, by degree of composition',
      levels: [
        { label: 'Model 01 — Point Intelligence', text: 'Deploy a single capability. Example: Vision AI for visual inspection.' },
        { label: 'Model 02 — Connected Intelligence', text: 'Connect multiple products. Example: Vision AI, Edge AI, Digital Twins and AI Agents.' },
        { label: 'Model 03 — Full Intelligence Stack', text: 'Connect perception, reasoning, context, agency and enterprise orchestration, from Vision AI through to Business Cloud.' },
      ] },
    { kind: 'p', text: 'The architecture can scale according to the problem.' },

    { kind: 'h2', id: 'example-loops', text: 'Example Intelligence Loops' },
    { kind: 'h3', id: 'loop-industrial', text: 'Loop 01 — Industrial Operations' },
    { kind: 'flow', steps: ['Vision AI detects an anomaly', 'Edge AI validates the signal', 'Digital Twin identifies the asset', 'Generative & Cognitive AI evaluates causes', 'AI Agent retrieves maintenance history', 'One AI OS coordinates', 'Business Cloud creates the workflow', 'Outcome observed'] },
    { kind: 'h3', id: 'loop-infrastructure', text: 'Loop 02 — Intelligent Infrastructure' },
    { kind: 'flow', steps: ['Drone AI observes infrastructure', 'Vision AI analyses conditions', 'Digital Twin updates the model', 'Simulation evaluates risks', 'AI Agents coordinate inspection', 'Business Cloud connects operational teams'] },
    { kind: 'h3', id: 'loop-enterprise', text: 'Loop 03 — Enterprise Automation' },
    { kind: 'flow', steps: ['A business event occurs', 'Business Cloud captures the signal', 'Generative & Cognitive AI interprets', 'AI Agents coordinate tasks', 'One AI OS applies permissions', 'Enterprise systems execute', 'Feedback returns'] },

    { kind: 'h2', id: 'deployment-patterns', text: 'Enterprise Deployment Patterns' },
    { kind: 'p', text: 'SVARA products can support different transformation paths.' },
    { kind: 'defs', items: [
      { term: 'Start with perception', text: 'For physical environments: Vision AI → Edge AI → Digital Twins.' },
      { term: 'Start with enterprise intelligence', text: 'For knowledge and workflow challenges: Generative AI → AI Agents → One AI OS.' },
      { term: 'Start with simulation', text: 'For complex environments: Digital Twins → Simulation → AI Agents.' },
      { term: 'Start with orchestration', text: 'For organisations already using multiple AI systems: One AI OS → existing models → existing agents → enterprise systems.' },
    ] },
    { kind: 'p', text: 'The objective is not to force a single transformation path. It is to compose the appropriate intelligence architecture.' },

    { kind: 'h2', id: 'governance', text: 'Governance and Control' },
    { kind: 'p', text: 'As products become more connected, governance must operate across the stack. Every layer requires clear boundaries.' },
    { kind: 'defs', items: [
      { term: 'Perception', text: 'What information can be collected?' },
      { term: 'Context', text: 'What data can intelligence access?' },
      { term: 'Reasoning', text: 'Which models can be used?' },
      { term: 'Agency', text: 'What tools can agents access?' },
      { term: 'Orchestration', text: 'Who defines permissions?' },
      { term: 'Action', text: 'Which actions require approval?' },
    ] },
    { kind: 'p', text: 'The objective is not unrestricted automation.' },
    { kind: 'statement', text: 'It is controlled intelligence with defined autonomy.' },

    { kind: 'h2', id: 'building', text: 'Building With the SVARA Stack' },
    { kind: 'p', text: 'The recommended approach is not to deploy every product simultaneously. Instead:' },
    { kind: 'ol', items: [
      'Identify the intelligence gap. Where is information failing to become action?',
      'Map the current stack. What systems, data and workflows already exist?',
      'Start with the entry point — perception, context, reasoning or automation.',
      'Add the required intelligence layer. Introduce the appropriate SVARA capability.',
      'Connect the loop. Ensure outcomes can move between systems.',
      'Orchestrate. Coordinate intelligence as complexity grows.',
      'Govern. Define permissions, oversight and accountability.',
      'Expand. Add additional capabilities as the intelligence architecture matures.',
    ] },

    { kind: 'h2', id: 'future', text: 'The Future of Product Engineering' },
    { kind: 'p', text: 'The future of technology products may become increasingly composable.' },
    { kind: 'p', text: 'Customers will not simply purchase applications. They will assemble intelligence capabilities.' },
    { kind: 'p', text: 'One product will perceive. Another will understand. Another will simulate. Another will coordinate. Another will execute.' },
    { kind: 'p', text: 'The value will emerge through composition.' },
    { kind: 'p', text: 'This creates a new challenge for product engineering. Products must be designed not only around interfaces and features. They must be designed around:' },
    { kind: 'ul', items: [
      'interoperability;', 'context;', 'intelligence flows;', 'APIs;',
      'agent interaction;', 'orchestration;', 'governance.',
    ] },
    { kind: 'statement', text: 'The future product is not always a destination. Sometimes it is a capability inside a larger system.' },
  ],

  closing: {
    heading: 'Closing Perspective',
    paragraphs: [
      'SVARA’s product ecosystem begins with a simple principle: intelligence should move.',
      'It should move from reality into perception. From perception into understanding. From understanding into context. From context into reasoning. From reasoning into simulation. From simulation into agency. From agency into action. And from action back into learning.',
      'That is how individual products become part of something larger.',
      'Not a collection of disconnected AI tools. But a composable intelligence stack.',
      'From vision, to understanding, to context, to reasoning, to simulation, to autonomous agency, to enterprise action.',
      'Build individual intelligence. Connect collective intelligence. Create continuous intelligence loops.',
    ],
  },

  cta: {
    headline: 'PRODUCT ENGINEERING — FROM VISION AI TO AUTONOMOUS AGENTS.',
    body: 'From edge perception to enterprise-wide automation. Explore the products that compose into the SVARA intelligence stack.',
    links: [
      { label: 'Explore Vision AI', to: '/products/vision-ai' },
      { label: 'Explore AI Agents', to: '/products/ai-agents' },
      { label: 'Explore AI OS', to: '/products/ai-os' },
      { label: 'Explore the SVARA Ecosystem', to: '/ecosystem' },
    ],
  },

  related: [
    { label: 'Vision AI', to: '/products/vision-ai' },
    { label: 'Drone AI', to: '/products/drone-ai' },
    { label: 'Edge AI', to: '/products/edge-ai' },
    { label: 'Digital Twin', to: '/products/digital-twin' },
    { label: 'AI Agents', to: '/products/ai-agents' },
    { label: 'AI OS', to: '/products/ai-os' },
    { label: 'Business Cloud', to: '/products/business-cloud' },
    { label: 'Digital Engineering', to: '/divisions/digital-engineering' },
    { label: 'Digital Growth', to: '/divisions/digital-growth' },
  ],
}
