// WHITE PAPER 02 — "The Intelligence Loop"
//
// design: 'schematic' — the dark instrument treatment. Chosen because the paper's subject
// IS an architecture: a document arguing that intelligence is a closed loop reads better
// as a system diagram than as printed prose. Copy is VERBATIM from the approved draft.
//
// The first `flow` block is load-bearing: PaperSchematic lifts it onto the cover as the
// loop device, so the cover and the body cannot drift apart. Keep it first.
import type { Insight } from './types'

export const theIntelligenceLoop: Insight = {
  slug: 'the-intelligence-loop',
  kind: 'paper',
  design: 'schematic',
  title: 'The Intelligence Loop',
  subtitle: 'How Perception, Context, Reasoning, Simulation and Action Close Into One Operating System',
  seoTitle: 'The Intelligence Loop — SVARA Research White Paper',
  metaDescription:
    'The framework behind SVARA. How perception, understanding, context, reasoning, simulation, decision, action, observation and adaptation close into one continuous operating loop.',
  category: 'Autonomous Intelligence / Deep Tech',
  contentType: 'White Paper',
  searchIntent: 'Informational',
  readingTime: '30–40 minutes',
  extent: '30–40 pages',
  published: '2026-09-02',
  primaryKeywords: [
    'intelligence loop', 'closed-loop AI', 'autonomous intelligence architecture',
    'AI operating system', 'systems of intelligence',
  ],
  secondaryKeywords: [
    'perception', 'context engineering', 'AI reasoning', 'simulation', 'AI agents',
    'digital twins', 'edge intelligence', 'AI orchestration', 'human in the loop',
  ],
  dek: 'Intelligence becomes operational when perception, understanding, reasoning and action are connected through continuous feedback. A model can answer a question; an intelligent loop can participate in an evolving environment.',

  corePosition: {
    heading: 'Executive Premise',
    paragraphs: [
      'Artificial intelligence is often discussed as a collection of separate technologies: computer vision, generative AI, AI agents, digital twins, simulation, automation.',
      'Each capability is powerful on its own. But the real transformation begins when these capabilities stop operating as isolated tools.',
      'A camera detects something. An AI system understands what it sees. Context explains why it matters. A reasoning system evaluates possible responses. Simulation explores potential consequences. An AI agent coordinates the required actions. The outcome is observed. The system learns. And the loop begins again.',
      'This is The Intelligence Loop.',
      'For SVARA, this loop represents more than a technology architecture. It is a framework for understanding how the next generation of intelligent systems will operate.',
    ],
  },

  blocks: [
    { kind: 'h2', id: 'executive-summary', text: 'Executive Summary' },
    // FIRST flow — lifted onto the cover as the loop device. Keep it here.
    { kind: 'flow', steps: ['Perceive', 'Understand', 'Contextualise', 'Reason', 'Simulate', 'Decide', 'Act', 'Observe', 'Adapt'] },
    { kind: 'p', text: 'For decades, technology has largely operated through separate systems.' },
    { kind: 'p', text: 'One system stores customer information. Another manages operations. Another generates reports. Another monitors infrastructure. Another controls workflows.' },
    { kind: 'p', text: 'People sit between these systems. They collect information, interpret events, connect context, make decisions and initiate action.' },
    { kind: 'p', text: 'Artificial intelligence introduces the possibility of redesigning this relationship.' },
    { kind: 'p', text: 'The future may not involve replacing every existing system. Instead, intelligence can become a layer that connects them.' },
    { kind: 'p', text: 'The loop is continuous.' },
    { kind: 'p', text: 'That continuity is the difference between isolated AI functionality and operational intelligence.' },
    { kind: 'statement', text: 'A model can answer a question. An intelligent loop can participate in an evolving environment.' },

    { kind: 'h2', id: 'fragmented', text: 'The Problem With Fragmented Intelligence' },
    { kind: 'p', text: 'Many organisations are already investing in AI. However, AI adoption can become fragmented.' },
    { kind: 'p', text: 'One team deploys a chatbot. Another uses predictive analytics. Another experiments with AI agents. Another builds automation. Another explores computer vision.' },
    { kind: 'p', text: 'The result can be a collection of intelligent capabilities without a connected intelligence architecture.' },
    { kind: 'statement', text: 'Intelligence can exist without intelligence being operational.' },
    { kind: 'p', text: 'An AI model may detect a pattern. But what happens next?' },
    { kind: 'p', text: 'A dashboard may display the insight. But who sees it?' },
    { kind: 'p', text: 'An AI agent may be capable of taking action. But what context does it have?' },
    { kind: 'p', text: 'A simulation may predict an outcome. But how does that prediction influence operations?' },
    { kind: 'p', text: 'The missing component is the connection between stages.' },
    { kind: 'p', text: 'Intelligence creates value when insight can move through a structured path toward appropriate action. The Intelligence Loop provides that structure.' },

    { kind: 'h2', id: 'introducing', text: 'Introducing The Intelligence Loop' },
    { kind: 'p', text: 'The SVARA Intelligence Loop is a continuous architecture connecting the environment, intelligence and action.' },
    { kind: 'defs', items: [
      { term: '01 — Perceive', text: 'What is happening?' },
      { term: '02 — Understand', text: 'What does it mean?' },
      { term: '03 — Contextualise', text: 'Why does it matter?' },
      { term: '04 — Reason', text: 'What are the possibilities?' },
      { term: '05 — Simulate', text: 'What could happen?' },
      { term: '06 — Decide', text: 'What should happen next?' },
      { term: '07 — Act', text: 'What can be done?' },
      { term: '08 — Observe', text: 'What actually happened?' },
      { term: '09 — Adapt', text: 'What should change?' },
    ] },
    { kind: 'p', text: 'This architecture can operate across both physical and digital environments. The loop can begin with:' },
    { kind: 'ul', items: [
      'a camera;', 'a sensor;', 'an enterprise event;', 'a customer interaction;',
      'a financial transaction;', 'a supply chain disruption;', 'a system anomaly;', 'a human request.',
    ] },
    { kind: 'p', text: 'The starting point is not important.' },
    { kind: 'statement', text: 'The continuity of the loop is.' },

    { kind: 'h2', id: 'perception', text: 'Stage One: Perception' },
    { kind: 'p', text: 'Every intelligence system begins with a signal. The system must first observe the environment.' },
    { kind: 'p', text: 'In physical environments, this may involve cameras, sensors, drones, robotics, IoT devices and machines.' },
    { kind: 'p', text: 'In digital environments, perception may involve applications, APIs, enterprise data, transactions, documents, communication systems and user behaviour.' },
    { kind: 'p', text: 'Vision AI expands the perception layer by allowing systems to extract structured information from visual environments. Edge AI can process signals closer to where they originate.' },
    { kind: 'p', text: 'The goal is to reduce the distance between event and understanding.' },
    { kind: 'statement', text: 'Perception answers: what is happening right now?' },

    { kind: 'h2', id: 'understanding', text: 'Stage Two: Understanding' },
    { kind: 'p', text: 'Perception creates information. Understanding creates meaning.' },
    { kind: 'p', text: 'Consider a camera that identifies a vehicle. That is perception.' },
    { kind: 'p', text: 'Understanding may determine:' },
    { kind: 'ul', items: [
      'what type of vehicle it is;', 'where it is located;', 'whether it is authorised;',
      'what behaviour it is demonstrating;', 'whether the situation is normal.',
    ] },
    { kind: 'p', text: 'Raw detection does not automatically create operational intelligence. The system must interpret the event.' },
    { kind: 'statement', text: 'Understanding transforms signal into meaning.' },

    { kind: 'h2', id: 'context', text: 'Stage Three: Context' },
    { kind: 'p', text: 'Meaning alone may still be insufficient. A system needs to understand the broader environment.' },
    { kind: 'p', text: 'Imagine an operational alert. The system detects an unusual temperature increase. Is that a problem?' },
    { kind: 'p', text: 'Context may reveal:' },
    { kind: 'ul', items: [
      'the machine recently changed modes;', 'external conditions changed;',
      'maintenance is scheduled;', 'demand increased;', 'the sensor is malfunctioning.',
    ] },
    { kind: 'p', text: 'Without context, intelligence can produce the wrong interpretation.' },
    { kind: 'p', text: 'The context layer connects information across time, systems, assets, relationships, historical events and operational constraints.' },
    { kind: 'p', text: 'Digital twins can play an important role here. They can create structured representations of systems and their relationships.' },
    { kind: 'statement', text: 'Context answers: what does this event mean in this specific environment?' },

    { kind: 'h2', id: 'reasoning', text: 'Stage Four: Reasoning' },
    { kind: 'p', text: 'Once the system understands what is happening and why it may matter, it can begin evaluating possibilities.' },
    { kind: 'p', text: 'Reasoning asks: what caused this? What information is missing? What are the available options? Which option is appropriate?' },
    { kind: 'p', text: 'This stage may combine:' },
    { kind: 'ul', items: [
      'generative AI;', 'cognitive AI;', 'machine learning;', 'rules;',
      'knowledge systems;', 'retrieval systems;', 'domain-specific models.',
    ] },
    { kind: 'p', text: 'The goal is not simply to generate an answer. It is to develop a structured path toward a decision.' },
    { kind: 'p', text: 'Traditional automation may operate through IF X → DO Y. Reasoning introduces another possibility:' },
    { kind: 'flow', steps: ['If X', 'Understand context', 'Evaluate options', 'Determine appropriate response'] },

    { kind: 'h2', id: 'simulation', text: 'Stage Five: Simulation' },
    { kind: 'p', text: 'One of the most powerful capabilities in the Intelligence Loop is the ability to explore possibilities before acting.' },
    { kind: 'p', text: 'Instead of immediately responding, the system can ask:' },
    { kind: 'ul', items: [
      'What happens if we do nothing?', 'What happens if we choose Option A?',
      'What happens if conditions continue changing?',
    ] },
    { kind: 'p', text: 'Digital twins can provide the representation. Simulation models possible outcomes. AI can interpret the results.' },
    { kind: 'p', text: 'This transforms intelligence from reactive toward anticipatory.' },
    { kind: 'statement', text: 'The ability to explore consequences before acting may become one of the defining capabilities of advanced intelligent systems.' },

    { kind: 'h2', id: 'decision', text: 'Stage Six: Decision' },
    { kind: 'p', text: 'A decision layer converts reasoning and simulation into an actionable direction.' },
    { kind: 'p', text: 'However, the system must operate within defined boundaries.' },
    { kind: 'p', text: 'A decision is not simply: what is the best possible action? It must also consider:' },
    { kind: 'ul', items: [
      'What is permitted?', 'What is the confidence level?', 'What is the potential impact?',
      'Is human approval required?', 'Is the action reversible?',
    ] },
    { kind: 'p', text: 'Decision intelligence therefore combines capability with constraint.' },
    { kind: 'statement', text: 'The most capable action is not always the most appropriate action.' },

    { kind: 'h2', id: 'action', text: 'Stage Seven: Action' },
    { kind: 'p', text: 'Intelligence creates operational value when it can influence the environment.' },
    { kind: 'p', text: 'Action may include:' },
    { kind: 'ul', items: [
      'sending an alert;', 'updating an enterprise system;', 'triggering a workflow;',
      'assigning a task;', 'communicating with a customer;', 'adjusting a process;',
      'activating a machine;', 'escalating to a human.',
    ] },
    { kind: 'p', text: 'AI agents can play a critical role at this stage. They can connect reasoning with tools and systems.' },
    { kind: 'p', text: 'A specialised agent may:' },
    { kind: 'ul', items: [
      'receive the decision;', 'determine the required tools;', 'execute the permitted steps;',
      'monitor completion;', 'report the outcome.',
    ] },
    { kind: 'p', text: 'Action should never exist without boundaries.' },
    { kind: 'statement', text: 'The system must know what it can do. But equally: what it must not do.' },

    { kind: 'h2', id: 'observation', text: 'Stage Eight: Observation' },
    { kind: 'p', text: 'Action is not the end of intelligence. The system must observe the result.' },
    { kind: 'p', text: 'Did the action work? Did the environment change? Did an unexpected consequence occur?' },
    { kind: 'p', text: 'This creates a critical feedback mechanism.' },
    { kind: 'flow', steps: ['Action', 'Outcome', 'Observation', 'New Information'] },
    { kind: 'p', text: 'The outcome becomes the next signal entering the loop.' },

    { kind: 'h2', id: 'adaptation', text: 'Stage Nine: Adaptation' },
    { kind: 'p', text: 'Adaptation does not necessarily mean uncontrolled self-modification. In enterprise systems, adaptation should occur within defined frameworks.' },
    { kind: 'p', text: 'The system may:' },
    { kind: 'ul', items: [
      'update its understanding;', 'change the next recommended action;', 'improve prioritisation;',
      'identify patterns;', 'adjust operational strategies.',
    ] },
    { kind: 'p', text: 'The key principle is feedback.' },
    { kind: 'p', text: 'An intelligent system that acts without observing outcomes cannot meaningfully improve its decisions.' },
    { kind: 'statement', text: 'The Intelligence Loop closes when the consequences of action become new information.' },

    { kind: 'h2', id: 'closed-loop-architecture', text: 'The Closed-Loop Intelligence Architecture' },
    { kind: 'p', text: 'The complete SVARA framework can be represented as:' },
    { kind: 'stack', layers: [
      { name: 'Reality', items: ['Physical and digital environments'] },
      { name: 'Perception', items: ['Vision AI', 'Sensors', 'IoT', 'Enterprise Data'] },
      { name: 'Understanding', items: ['Classification', 'Interpretation', 'Event Detection'] },
      { name: 'Context', items: ['Knowledge', 'History', 'Relationships', 'Digital Twins'] },
      { name: 'Reasoning', items: ['Generative AI', 'Cognitive AI', 'Predictive Intelligence'] },
      { name: 'Simulation', items: ['Scenarios', 'Forecasting', 'Digital Environments'] },
      { name: 'Decision', items: ['Objectives', 'Constraints', 'Permissions'] },
      { name: 'Agency', items: ['AI Agents', 'Tools', 'Workflows'] },
      { name: 'Action', items: ['Humans', 'Software', 'Machines', 'Systems'] },
      { name: 'Observation', items: ['Outcomes', 'Feedback', 'New Signals'] },
      { name: 'Adaptation', items: ['Evaluation', 'Optimisation', 'Learning'] },
    ] },
    { kind: 'statement', text: 'And the loop continues.' },

    { kind: 'h2', id: 'ai-agents', text: 'The Role of AI Agents' },
    { kind: 'p', text: 'AI agents are not the entire Intelligence Loop. They are one of the mechanisms through which intelligence becomes operational.' },
    { kind: 'p', text: 'An agent can potentially investigate, retrieve information, plan, use tools, coordinate tasks and execute actions.' },
    { kind: 'p', text: 'In a mature architecture, multiple agents may collaborate.' },
    { kind: 'stack', layers: [
      { name: 'Perception Agent', items: ['Monitors incoming signals'] },
      { name: 'Context Agent', items: ['Retrieves relevant information'] },
      { name: 'Reasoning Agent', items: ['Evaluates the situation'] },
      { name: 'Simulation Agent', items: ['Explores possible outcomes'] },
      { name: 'Execution Agent', items: ['Coordinates approved action'] },
      { name: 'Observation Agent', items: ['Monitors the result'] },
    ] },
    { kind: 'statement', text: 'The Intelligence Loop provides the architecture. AI agents provide distributed capability inside that architecture.' },

    { kind: 'h2', id: 'digital-twins', text: 'Digital Twins as the Context and Simulation Layer' },
    { kind: 'p', text: 'Digital twins can occupy a particularly important position inside the loop.' },
    { kind: 'p', text: 'They help create a structured representation of a physical or operational environment. This representation can provide:' },
    { kind: 'ul', items: ['context;', 'relationships;', 'historical information;', 'operational state;', 'simulation capabilities.'] },
    { kind: 'p', text: 'The Intelligence Loop can therefore connect:' },
    { kind: 'flow', steps: ['Reality', 'Digital Representation', 'Simulation', 'Decision', 'Action', 'New Reality'] },
    { kind: 'p', text: 'The digital twin is not simply a visual model. Within the loop, it can become part of the intelligence infrastructure.' },

    { kind: 'h2', id: 'edge', text: 'Edge Intelligence and Real-Time Response' },
    { kind: 'p', text: 'Not every decision needs to travel through a centralised system. Some environments require intelligence closer to where events occur.' },
    { kind: 'flow', steps: ['Camera', 'Edge AI', 'Event Detection', 'Local Decision', 'Action'] },
    { kind: 'p', text: 'Only meaningful information may need to enter the wider intelligence architecture. This can support:' },
    { kind: 'ul', items: ['faster response;', 'reduced latency;', 'more efficient data movement;', 'greater resilience.'] },
    { kind: 'p', text: 'Edge intelligence becomes the outer layer of the loop.' },
    { kind: 'p', text: 'The intelligence architecture can then extend from edge, to cloud, to enterprise systems — and back again.' },

    { kind: 'h2', id: 'ai-os', text: 'The AI OS: Orchestrating the Loop' },
    { kind: 'p', text: 'As intelligence systems become more complex, another challenge emerges: who coordinates the loop?' },
    { kind: 'p', text: 'An organisation may eventually have multiple AI models, specialised agents, digital twins, automation systems, enterprise software, data platforms and human operators.' },
    { kind: 'p', text: 'The AI OS becomes the orchestration layer. Its responsibilities may include:' },
    { kind: 'ul', items: [
      'routing intelligence tasks;', 'coordinating agents;', 'managing context;',
      'applying permissions;', 'selecting models;', 'monitoring activity;', 'maintaining observability.',
    ] },
    { kind: 'p', text: 'The AI OS does not replace every layer. It coordinates them.' },
    { kind: 'statement', text: 'The Intelligence Loop describes how intelligence moves. The AI OS helps coordinate where it moves and how it operates.' },

    { kind: 'h2', id: 'human', text: 'Human Intelligence Inside the Loop' },
    { kind: 'p', text: 'Autonomous intelligence should not assume that humans disappear from the system.' },
    { kind: 'p', text: 'Human involvement can exist at different points.' },
    { kind: 'defs', items: [
      { term: 'Human-in-the-loop', text: 'A person approves specific decisions.' },
      { term: 'Human-on-the-loop', text: 'The system operates independently while humans monitor performance.' },
      { term: 'Human-as-the-strategic-layer', text: 'Humans define objectives, boundaries, policies and priorities.' },
    ] },
    { kind: 'p', text: 'The objective is not to remove human intelligence. It is to redesign where human attention creates the greatest value.' },
    { kind: 'p', text: 'The loop should escalate when:' },
    { kind: 'ul', items: [
      'confidence is low;', 'impact is high;', 'the decision exceeds permissions;',
      'conflicting objectives exist.',
    ] },

    { kind: 'h2', id: 'maturity', text: 'The Intelligence Loop Maturity Model' },
    { kind: 'scale',
      caption: 'The intelligence loop maturity model',
      levels: [
        { label: 'Level 01 — Reactive', text: 'Systems detect events. Example: alerts and dashboards.' },
        { label: 'Level 02 — Informed', text: 'Systems add analysis and context. Example: AI-assisted insights.' },
        { label: 'Level 03 — Predictive', text: 'Systems anticipate potential outcomes. Example: forecasting and anomaly detection.' },
        { label: 'Level 04 — Simulated', text: 'Systems evaluate possible actions before execution. Example: digital twins and scenario modelling.' },
        { label: 'Level 05 — Agentic', text: 'AI agents coordinate actions. Example: goal-driven workflows and tool use.' },
        { label: 'Level 06 — Closed-Loop', text: 'The system connects perception, context, reasoning, action and feedback. This is where intelligence becomes continuous.' },
        { label: 'Level 07 — Adaptive', text: 'The organisation operates multiple interconnected intelligence loops that continuously respond to changing environments. This represents the potential architecture of the autonomous enterprise.' },
      ] },

    { kind: 'h2', id: 'applications', text: 'Enterprise Applications' },
    { kind: 'h3', id: 'app-manufacturing', text: 'Intelligent Manufacturing' },
    { kind: 'flow', steps: ['Sensor identifies abnormal behaviour', 'Edge AI analyses the event', 'Digital twin provides context', 'Simulation explores responses', 'AI agent coordinates maintenance', 'Outcome is monitored', 'Loop updates'] },
    { kind: 'h3', id: 'app-customer', text: 'Intelligent Customer Operations' },
    { kind: 'flow', steps: ['Customer makes a request', 'AI understands the intent', 'Context is retrieved', 'System evaluates resolutions', 'Agent performs approved actions', 'Result is measured', 'Next interaction benefits'] },
    { kind: 'h3', id: 'app-infrastructure', text: 'Smart Infrastructure' },
    { kind: 'flow', steps: ['Sensors and Vision AI observe', 'Edge identifies meaningful events', 'Digital representations give context', 'AI prioritises', 'Simulation evaluates interventions', 'Approved systems act', 'Result feeds back'] },
    { kind: 'h3', id: 'app-supply-chain', text: 'Supply Chain Intelligence' },
    { kind: 'flow', steps: ['A disruption occurs', 'System detects the event', 'Supplier, inventory and logistics data retrieved', 'AI evaluates responses', 'Scenarios are simulated', 'Agents coordinate the response', 'Outcome observed'] },

    { kind: 'h2', id: 'designing', text: 'Designing an Intelligence Loop' },
    { kind: 'p', text: 'Organisations should begin with a specific operational problem. Not “where can we use AI?” but:' },
    { kind: 'statement', text: 'Where is there a decision loop that can become more intelligent?' },
    { kind: 'ol', items: [
      'Identify the environment. What is changing?',
      'Identify the signal. What information can reveal that change?',
      'Define the context. What does the system need to understand?',
      'Define the decision. What decision should improve?',
      'Map possible actions. What can happen next?',
      'Define boundaries. What is permitted?',
      'Create feedback. How will the outcome be measured?',
      'Close the loop. How does the result influence the next cycle?',
    ] },

    { kind: 'h2', id: 'governance', text: 'Governance and Boundaries' },
    { kind: 'p', text: 'A closed loop without boundaries can create unacceptable risk.' },
    { kind: 'p', text: 'Every Intelligence Loop should define:' },
    { kind: 'defs', items: [
      { term: 'Objectives', text: 'What is the system optimising for?' },
      { term: 'Context Boundaries', text: 'What information can it access?' },
      { term: 'Decision Boundaries', text: 'What types of decisions can it make?' },
      { term: 'Action Boundaries', text: 'What can it execute?' },
      { term: 'Escalation Rules', text: 'When must a human intervene?' },
      { term: 'Observability', text: 'Can decisions and actions be monitored?' },
      { term: 'Accountability', text: 'Who is responsible for the system?' },
    ] },
    { kind: 'statement', text: 'Intelligence is not defined only by what a system can do. It is also defined by its ability to recognise when it should not act.' },

    { kind: 'h2', id: 'systems-of-intelligence', text: 'From Systems of Record to Systems of Intelligence' },
    { kind: 'p', text: 'Enterprise technology has historically focused on recording what happened. CRM systems record customer interactions. ERP systems record business activity. Operational systems record events.' },
    { kind: 'p', text: 'The next evolution is the intelligence layer connecting those systems.' },
    { kind: 'p', text: 'Instead of simply asking what happened, organisations can increasingly ask:' },
    { kind: 'ul', items: [
      'What is happening now?', 'Why is it happening?', 'What could happen next?',
      'What are the available responses?', 'What should we do?', 'Execute the approved action.',
    ] },
    { kind: 'p', text: 'The shift is from systems of record, to systems of intelligence, to systems of action.' },
    { kind: 'statement', text: 'The Intelligence Loop connects all three.' },
  ],

  closing: {
    heading: 'Closing Perspective',
    paragraphs: [
      'The future of AI will not be defined only by more capable models. It will be defined by how intelligence connects with reality.',
      'A powerful model without perception lacks awareness. Perception without context lacks meaning. Reasoning without simulation may fail to anticipate consequences. Decision without action creates delay. Action without observation cannot learn.',
      'The Intelligence Loop connects these capabilities.',
      'Perceive — understand what is happening. Contextualise — understand why it matters. Reason — explore what is possible. Simulate — understand what could happen. Decide — determine what should happen. Act — move intelligence into the environment. Observe — measure the result. Adapt — learn from reality.',
      'Then begin again.',
      'Intelligence is not a destination. It is a loop.',
      'The organisations of the future will not simply deploy AI tools. They will design systems where intelligence continuously moves between reality and understanding, between possibility and decision, and between action and learning.',
    ],
  },

  cta: {
    headline: 'PERCEIVE THE WORLD. UNDERSTAND THE SIGNAL. SIMULATE THE POSSIBLE. ACT WITH INTELLIGENCE. LEARN FROM REALITY.',
    body: 'The Intelligence Loop — the framework behind autonomous intelligence.',
    links: [
      { label: 'Explore AI OS', to: '/products/ai-os' },
      { label: 'Explore AI Agents', to: '/products/ai-agents' },
      { label: 'Explore Digital Twins', to: '/products/digital-twin' },
      { label: 'Explore the SVARA Ecosystem', to: '/ecosystem' },
    ],
  },

  related: [
    { label: 'Deep Tech & Autonomous Intelligence', to: '/divisions/autonomous-intelligence' },
    { label: 'AI OS', to: '/products/ai-os' },
    { label: 'AI Agents', to: '/products/ai-agents' },
    { label: 'Digital Twin', to: '/products/digital-twin' },
    { label: 'Vision AI', to: '/products/vision-ai' },
    { label: 'Edge AI', to: '/products/edge-ai' },
  ],
}
