// TECHNICAL NOTE N2 — part of the SVARA Technical Notes series.
//
// kind: 'note' — the short-form treatment. Series position is NOT stored here: it is
// derived from registry order by seriesNotes(), so writing a fifth note cannot leave
// "N2 of 4" stale in four files at once.
//
// Copy is VERBATIM from the approved draft.
import type { Insight } from './types'

export const theCaseAgainstPointTools: Insight = {
  slug: 'the-case-against-point-tools',
  kind: 'note',
  title: 'The Case Against Point Tools',
  subtitle: 'Intelligence does not compound when every capability operates alone.',
  seoTitle: 'The Case Against Point Tools — SVARA Technical Note N2',
  metaDescription:
    'Why do isolated AI tools fail to create compounding intelligence? A SVARA technical note on composition, silos and connected intelligence architecture.',
  category: 'Technical Notes',
  contentType: 'Technical Note',
  searchIntent: 'Informational',
  readingTime: '4 minutes',
  published: '2026-09-02',
  primaryKeywords: ['AI point tools', 'connected intelligence', 'AI architecture vs tools'],
  secondaryKeywords: ['AI silos', 'composable AI', 'digital twins', 'AI agents'],
  dek: 'Why do isolated AI tools fail to create compounding intelligence?',

  blocks: [
    { kind: 'p', text: 'The AI market is full of specialised tools. A tool for writing. A tool for vision. A tool for analytics. A tool for automation. A tool for agents. A tool for simulation.' },
    { kind: 'p', text: 'Each may solve a specific problem.' },
    { kind: 'p', text: 'The challenge begins when organisations deploy intelligence as a collection of disconnected destinations.' },
    { kind: 'p', text: 'A vision system detects something. But the enterprise workflow does not know.' },
    { kind: 'p', text: 'An AI assistant generates insight. But it has no operational context.' },
    { kind: 'p', text: 'An agent can perform a task. But it cannot access the intelligence generated elsewhere.' },
    { kind: 'p', text: 'A digital twin visualises a system. But it does not participate in decision-making.' },
    { kind: 'p', text: 'This is the limitation of the point tool.' },
    { kind: 'statement', text: 'A point tool creates local intelligence. An architecture creates connected intelligence.' },
    { kind: 'p', text: 'The distinction matters because intelligence should compound. Information generated by one capability should be capable of improving another.' },
    { kind: 'p', text: 'A perception event can inform a digital twin. The digital twin can provide context to an AI model. The model can inform an agent. The agent can initiate a workflow. The outcome can become feedback.' },
    { kind: 'p', text: 'This creates a connected system.' },
    { kind: 'flow', steps: ['Perception', 'Context', 'Reasoning', 'Agency', 'Action', 'Learning'] },
    { kind: 'p', text: 'The problem with point tools is not that they lack capability.' },
    { kind: 'p', text: 'The problem is that capability without composition eventually creates another silo.' },
    { kind: 'p', text: 'The architectural question should therefore shift from “what AI tool should we buy?” to “how will this capability participate in our intelligence system?”' },
  ],

  closing: {
    heading: '',
    paragraphs: ['The future is not fewer AI tools. It is better-connected intelligence.'],
  },

  cta: {
    headline: 'CAPABILITY WITHOUT COMPOSITION IS ANOTHER SILO.',
    body: 'Explore how the SVARA products compose into one intelligence stack.',
    links: [
      { label: 'Product Engineering', to: '/insights/product-engineering' },
      { label: 'AI OS', to: '/products/ai-os' },
      { label: 'The SVARA Ecosystem', to: '/ecosystem' },
    ],
  },
  related: [
    { label: 'AI OS', to: '/products/ai-os' },
    { label: 'AI Agents', to: '/products/ai-agents' },
  ],
}
