// INSIGHT 02 — "Computer Vision Explained"
//
// Cluster article under the Deep Tech & Autonomous Intelligence pillar; it links back to
// insight 01 and forward to the product pages. Copy is VERBATIM from the approved draft.
// The hedging ("may", "can", "potential") and the privacy/governance caveats are load-
// bearing — this piece touches workplace monitoring and retail footfall, where an
// unhedged capability claim would be both a content-audit failure and a compliance one.
import type { Insight } from './types'

export const whatIsComputerVision: Insight = {
  slug: 'what-is-computer-vision',
  title: 'Computer Vision Explained',
  subtitle: 'How AI Is Teaching Machines to Understand the Physical World',
  seoTitle: 'What Is Computer Vision? How AI Understands Images and the Physical World',
  metaDescription:
    'Computer vision enables AI systems to analyse images, video and visual environments. Learn how computer vision works, its applications, benefits and role in autonomous intelligence.',
  category: 'Deep Tech & Autonomous Intelligence',
  contentType: 'Cluster Article',
  searchIntent: 'Informational',
  readingTime: '9–11 minutes',
  published: '2026-09-02',
  primaryKeywords: [
    'computer vision', 'what is computer vision', 'AI computer vision',
    'computer vision systems', 'computer vision applications',
  ],
  secondaryKeywords: [
    'machine vision', 'image recognition', 'object detection', 'visual AI',
    'real-time computer vision', 'edge AI', 'autonomous systems', 'vision AI',
  ],
  dek: 'Computer vision turns pixels into perception — and inside a connected architecture, that perception becomes the sensory layer of autonomous intelligence.',
  heroImage: {
    name: 'what-is-computer-vision',
    alt:
      'A five-stage AI perception pipeline: a real-world street scene, multi-camera capture, object detection and tracking with bounding boxes on a pedestrian and vehicles, neural processing through detection and segmentation models, and autonomous decision pathways ending in a yield-and-stop decision at 96% confidence.',
  },

  blocks: [
    { kind: 'h2', id: 'what-is-computer-vision', text: 'What Is Computer Vision?' },
    { kind: 'p', text: 'Computer vision is a field of artificial intelligence that enables machines to analyse, interpret and derive meaningful information from images, video and other visual inputs.' },
    { kind: 'p', text: 'In simple terms, computer vision gives digital systems the ability to process visual information and convert it into data, understanding and potentially action.' },
    { kind: 'p', text: 'A camera alone captures pixels.' },
    { kind: 'p', text: 'A computer vision system attempts to answer questions about what those pixels represent.' },
    { kind: 'p', text: 'For example:' },
    { kind: 'ul', items: [
      'What objects are visible?', 'Where are they located?', 'Is something moving?',
      'Has something changed?', 'Is there an anomaly?', 'Is an object damaged?',
      'Is a person wearing required safety equipment?', 'Is a vehicle entering a restricted area?',
    ] },
    { kind: 'p', text: 'This makes computer vision one of the most important perception technologies in modern AI.' },
    { kind: 'p', text: 'If autonomous intelligence needs to understand the physical world, computer vision can become one of its primary senses.' },

    { kind: 'h2', id: 'how-does-computer-vision-work', text: 'How Does Computer Vision Work?' },
    { kind: 'p', text: 'Computer vision transforms visual input into information that software systems can interpret.' },
    { kind: 'p', text: 'A simplified process looks like this:' },
    { kind: 'flow', steps: ['Camera or Sensor', 'Visual Data', 'AI Model', 'Recognition', 'Context', 'Decision', 'Action'] },
    { kind: 'p', text: 'The exact architecture depends on the application, but most computer vision systems involve several core stages.' },

    { kind: 'h3', id: 'capturing-visual-data', text: '1. Capturing Visual Data' },
    { kind: 'p', text: 'The process begins with visual input.' },
    { kind: 'p', text: 'This may come from:' },
    { kind: 'ul', items: [
      'cameras;', 'video streams;', 'drones;', 'industrial imaging systems;', 'satellites;',
      'medical imaging equipment;', 'mobile devices;', 'autonomous machines.',
    ] },
    { kind: 'p', text: 'The system receives an image or sequence of images as raw data.' },
    { kind: 'p', text: 'At this stage, the machine does not inherently understand what it is seeing.' },
    { kind: 'p', text: 'It is processing visual information as numerical data.' },

    { kind: 'h3', id: 'processing-the-image', text: '2. Processing the Image' },
    { kind: 'p', text: 'Before or during AI analysis, visual data may be processed to improve its usability.' },
    { kind: 'p', text: 'This can include:' },
    { kind: 'ul', items: ['resizing;', 'normalisation;', 'noise reduction;', 'contrast adjustment;', 'frame extraction;', 'feature preparation.'] },
    { kind: 'p', text: 'The objective is to prepare information for the model or algorithm responsible for analysing it.' },
    { kind: 'p', text: 'In real-world environments, this can be challenging.' },
    { kind: 'ul', items: ['Lighting changes.', 'Objects move.', 'Cameras shake.', 'Weather changes.', 'Parts of objects may be hidden.'] },
    { kind: 'p', text: 'A computer vision system must therefore be designed for the conditions in which it will operate.' },

    { kind: 'h3', id: 'recognition-and-detection', text: '3. Recognition and Detection' },
    { kind: 'p', text: 'AI models can then analyse the visual input to identify patterns.' },
    { kind: 'p', text: 'Depending on the system, computer vision may perform tasks such as:' },
    { kind: 'defs', items: [
      { term: 'Image Classification', text: 'Determining what is represented in an image. For example: Is this image showing a defective product or a normal product?' },
      { term: 'Object Detection', text: 'Identifying both what an object is and where it is located within an image. For example: Identify every vehicle within this video frame.' },
      { term: 'Object Tracking', text: 'Following identified objects across multiple video frames. For example: Track the movement of a vehicle through a facility.' },
      { term: 'Segmentation', text: 'Separating different regions or objects within an image at a more detailed level.' },
      { term: 'Anomaly Detection', text: 'Identifying visual patterns that differ from expected conditions. For example: Detect an unexpected crack, leak, obstruction or manufacturing defect.' },
    ] },

    { kind: 'h2', id: 'computer-vision-vs-image-recognition', text: 'Computer Vision vs Image Recognition' },
    { kind: 'p', text: 'Computer vision and image recognition are related, but they are not exactly the same.' },
    { kind: 'table',
      caption: 'Capability comparison: image recognition and computer vision',
      headers: ['Capability', 'Image Recognition', 'Computer Vision'],
      rows: [
        ['Identifies image content', '✓', '✓'],
        ['Detects multiple objects', 'Limited', '✓'],
        ['Locates objects', 'Limited', '✓'],
        ['Tracks movement', '✕', '✓'],
        ['Analyses video', 'Limited', '✓'],
        ['Understands spatial relationships', 'Limited', '✓'],
        ['Supports real-time decisions', 'Possible', '✓'],
      ] },
    { kind: 'p', text: 'Image recognition is generally focused on identifying or classifying what is present.' },
    { kind: 'p', text: 'Computer vision is broader.' },
    { kind: 'p', text: 'It can include recognition, detection, tracking, segmentation, visual analysis and the interpretation of changing environments.' },
    { kind: 'statement', text: 'Image recognition asks, “What is this?” Computer vision can ask, “What is happening?”' },
    { kind: 'p', text: 'That difference becomes increasingly important when AI moves from analysing static content toward operating in dynamic physical environments.' },

    { kind: 'h2', id: 'role-of-ai', text: 'The Role of AI in Computer Vision' },
    { kind: 'p', text: 'Traditional image-processing systems often relied heavily on manually designed rules.' },
    { kind: 'p', text: 'For example:' },
    { kind: 'p', text: 'If a pixel pattern matches a specific threshold, classify it as a defect.' },
    { kind: 'p', text: 'Modern AI-based computer vision can learn patterns from data.' },
    { kind: 'p', text: 'Machine learning and deep learning models can be trained to recognise characteristics associated with specific objects, conditions or events.' },
    { kind: 'p', text: 'This can enable systems to identify patterns that may be difficult to define through conventional rules alone.' },
    { kind: 'p', text: 'However, AI does not automatically guarantee accuracy.' },
    { kind: 'p', text: 'Performance can depend on:' },
    { kind: 'ul', items: [
      'the quality of training data;', 'how representative the data is;', 'camera quality;',
      'environmental conditions;', 'model architecture;', 'deployment environment;', 'testing and validation.',
    ] },
    { kind: 'p', text: 'A model trained in one environment may not perform identically in another.' },
    { kind: 'p', text: 'This is one of the reasons why real-world Vision AI requires more than simply connecting a model to a camera.' },

    { kind: 'h2', id: 'where-is-computer-vision-used', text: 'Where Is Computer Vision Used?' },
    { kind: 'p', text: 'Computer vision is increasingly being applied across physical and digital environments.' },

    { kind: 'h3', id: 'manufacturing-and-quality-inspection', text: 'Manufacturing and Quality Inspection' },
    { kind: 'p', text: 'Vision systems can inspect products, components and production processes.' },
    { kind: 'p', text: 'Potential applications include:' },
    { kind: 'ul', items: ['defect detection;', 'assembly verification;', 'surface inspection;', 'packaging analysis;', 'production monitoring.'] },
    { kind: 'p', text: 'Instead of relying entirely on manual inspection, AI-powered vision can continuously analyse visual information at scale.' },

    { kind: 'h3', id: 'safety-and-workplace-intelligence', text: 'Safety and Workplace Intelligence' },
    { kind: 'p', text: 'Computer vision can support the observation of environments where safety processes are important.' },
    { kind: 'p', text: 'Examples include identifying:' },
    { kind: 'ul', items: ['missing safety equipment;', 'restricted-area access;', 'hazardous conditions;', 'unsafe movement patterns;', 'potential obstructions.'] },
    { kind: 'p', text: 'The purpose is not simply surveillance.' },
    { kind: 'p', text: 'The more advanced opportunity is to convert visual signals into operational intelligence.' },

    { kind: 'h3', id: 'retail-and-physical-spaces', text: 'Retail and Physical Spaces' },
    { kind: 'p', text: 'Computer vision can help organisations understand activity within physical environments.' },
    { kind: 'p', text: 'Potential applications include:' },
    { kind: 'ul', items: ['customer flow analysis;', 'inventory observation;', 'queue detection;', 'shelf monitoring;', 'operational optimisation.'] },
    { kind: 'p', text: 'As with any technology that processes information relating to people, organisations need to consider privacy, security and applicable legal requirements.' },

    { kind: 'h3', id: 'logistics-and-supply-chains', text: 'Logistics and Supply Chains' },
    { kind: 'p', text: 'Visual AI can be applied to:' },
    { kind: 'ul', items: ['package recognition;', 'asset tracking;', 'warehouse monitoring;', 'loading verification;', 'infrastructure inspection.'] },
    { kind: 'p', text: 'When combined with operational data, computer vision can become part of a larger decision-making system.' },

    { kind: 'h3', id: 'infrastructure-and-asset-inspection', text: 'Infrastructure and Asset Inspection' },
    { kind: 'p', text: 'Drones, cameras and connected devices can capture visual information about:' },
    { kind: 'ul', items: ['buildings;', 'roads;', 'industrial assets;', 'energy infrastructure;', 'construction sites.'] },
    { kind: 'p', text: 'AI models can help analyse large volumes of visual data and identify areas that may require further human review.' },

    { kind: 'h2', id: 'computer-vision-and-edge-ai', text: 'Computer Vision and Edge AI' },
    { kind: 'p', text: 'One of the most important developments in modern Vision AI is the ability to run intelligence closer to where visual data is generated.' },
    { kind: 'p', text: 'This is known as Edge AI.' },
    { kind: 'p', text: 'Instead of transmitting every video frame to a remote cloud environment, an AI model may process data locally or near the source.' },
    { kind: 'p', text: 'This can provide potential advantages such as:' },
    { kind: 'ul', items: [
      'lower latency;', 'reduced bandwidth requirements;', 'faster responses;',
      'reduced dependence on continuous connectivity;', 'greater control over where certain data is processed.',
    ] },
    { kind: 'p', text: 'A simplified architecture may look like:' },
    { kind: 'flow', steps: ['Camera', 'Edge Device', 'Vision AI Model', 'Local Decision', 'Cloud / Enterprise System'] },
    { kind: 'p', text: 'This architecture can be particularly valuable when a system needs to respond quickly.' },
    { kind: 'p', text: 'For example:' },
    { kind: 'ol', items: [
      'A visual system identifies an anomaly.',
      'The Edge AI layer processes the event locally.',
      'An immediate response may be triggered.',
      'Relevant information can then be sent to other enterprise or cloud systems.',
    ] },
    { kind: 'statement', text: 'The closer intelligence moves to the point of observation, the faster perception can become action.' },

    { kind: 'h2', id: 'computer-vision-and-autonomous-intelligence', text: 'Computer Vision and Autonomous Intelligence' },
    { kind: 'p', text: 'Computer vision becomes even more powerful when connected to a broader autonomous intelligence architecture.' },
    { kind: 'p', text: 'Consider the difference between two systems.' },
    { kind: 'h3', id: 'system-one', text: 'System One: Vision Detection' },
    { kind: 'p', text: 'The system detects:' },
    { kind: 'p', text: 'An unauthorised object has entered an area.' },
    { kind: 'h3', id: 'system-two', text: 'System Two: Connected Autonomous Intelligence' },
    { kind: 'p', text: 'The system can potentially:' },
    { kind: 'ul', items: [
      'detect the object;', 'identify its location;', 'evaluate access information;',
      'determine whether the event represents a risk;', 'notify the appropriate team;',
      'trigger an approved workflow;', 'continue monitoring the situation;', 'escalate when required.',
    ] },
    { kind: 'p', text: 'The first system produces a detection.' },
    { kind: 'p', text: 'The second connects perception to context, reasoning and action.' },
    { kind: 'p', text: 'This is why computer vision is not simply an imaging technology.' },
    { kind: 'statement', text: 'Within a connected architecture, it can become the perception layer of autonomous intelligence.' },

    { kind: 'h3', id: 'computer-vision-and-ai-agents', text: 'Computer Vision + AI Agents' },
    { kind: 'p', text: 'AI agents can extend what happens after a visual event is detected.' },
    { kind: 'p', text: 'For example:' },
    { kind: 'p', text: 'Vision AI detects an equipment anomaly.' },
    { kind: 'p', text: 'An AI agent could then:' },
    { kind: 'ul', items: [
      'retrieve equipment history;', 'check recent maintenance records;', 'analyse related sensor data;',
      'create a maintenance request;', 'notify relevant personnel;', 'prepare a summary of the event.',
    ] },
    { kind: 'p', text: 'The architecture becomes:' },
    { kind: 'flow', steps: ['Vision', 'Detection', 'Context', 'AI Agent', 'Workflow', 'Action'] },
    { kind: 'p', text: 'This is an example of how specialised AI systems can work together.' },
    { kind: 'p', text: 'The future may involve fewer isolated applications and more connected intelligence pipelines.' },

    { kind: 'h3', id: 'computer-vision-and-digital-twins', text: 'Computer Vision + Digital Twins' },
    { kind: 'p', text: 'Computer vision can also contribute information to digital representations and simulation environments.' },
    { kind: 'p', text: 'Visual observations may help provide information about the state of a physical asset, process or environment.' },
    { kind: 'p', text: 'That information can potentially be combined with:' },
    { kind: 'ul', items: ['sensor data;', 'operational records;', 'historical data;', 'simulation models.'] },
    { kind: 'p', text: 'The result is a richer representation of what is happening in the physical world.' },
    { kind: 'p', text: 'This creates an important connection:' },
    { kind: 'statement', text: 'Computer vision observes reality. Digital twins and simulations help model and understand it.' },
    { kind: 'p', text: 'Together, these technologies can support more informed decision-making.' },

    { kind: 'h2', id: 'benefits', text: 'Key Benefits of Computer Vision' },
    { kind: 'defs', items: [
      { term: 'Continuous Observation', text: 'Computer vision systems can analyse visual environments continuously, subject to the capabilities and design of the underlying infrastructure.' },
      { term: 'Scale', text: 'AI can help analyse volumes of images and video that would be difficult to review manually.' },
      { term: 'Faster Detection', text: 'Potential events or anomalies can be identified more quickly than workflows that rely entirely on human observation.' },
      { term: 'Operational Intelligence', text: 'Visual data can become a source of structured information rather than remaining as unprocessed video or imagery.' },
      { term: 'Integration With Other Systems', text: 'Vision events can be connected with enterprise software, AI agents, alerts and automated workflows.' },
    ] },

    { kind: 'h2', id: 'challenges', text: 'Challenges in Building Real-World Vision AI' },
    { kind: 'p', text: 'The most impressive demonstration is not always the most difficult part.' },
    { kind: 'p', text: 'Deploying reliable computer vision in the real world introduces several challenges.' },

    { kind: 'h3', id: 'changing-environments', text: 'Changing Environments' },
    { kind: 'p', text: 'A model may encounter:' },
    { kind: 'ul', items: ['different lighting;', 'weather;', 'camera angles;', 'object variations;', 'motion;', 'partial visibility;', 'background changes.'] },
    { kind: 'p', text: 'The system must be evaluated against the conditions it will actually encounter.' },

    { kind: 'h3', id: 'data-quality', text: 'Data Quality' },
    { kind: 'p', text: 'Computer vision models depend heavily on the data used for development and evaluation.' },
    { kind: 'p', text: 'Poor or unrepresentative data can affect reliability.' },
    { kind: 'p', text: 'The question is not simply:' },
    { kind: 'p', text: 'How much data is available?' },
    { kind: 'p', text: 'It is also:' },
    { kind: 'statement', text: 'Does the data represent the real environment where the system will operate?' },

    { kind: 'h3', id: 'false-positives-and-negatives', text: 'False Positives and False Negatives' },
    { kind: 'p', text: 'A vision system may incorrectly identify an event.' },
    { kind: 'p', text: 'It may also fail to detect something important.' },
    { kind: 'p', text: 'The consequences depend on the use case.' },
    { kind: 'p', text: 'A recommendation system and a safety-critical environment require very different approaches to testing, thresholds and human oversight.' },

    { kind: 'h3', id: 'privacy-and-governance', text: 'Privacy and Governance' },
    { kind: 'p', text: 'Visual data may contain sensitive or personal information.' },
    { kind: 'p', text: 'Organisations need appropriate policies around:' },
    { kind: 'ul', items: ['data collection;', 'storage;', 'access;', 'retention;', 'security;', 'monitoring;', 'applicable legal requirements.'] },
    { kind: 'p', text: 'Responsible deployment is part of the technology architecture, not an afterthought.' },

    { kind: 'h2', id: 'svara-perspective', text: 'The SVARA Perspective: Vision Is the Beginning of Intelligence' },
    { kind: 'p', text: 'For SVARA, Vision AI is not simply about detecting objects in an image.' },
    { kind: 'p', text: 'It is about enabling systems to understand what is happening in the environments where organisations operate.' },
    { kind: 'defs', items: [
      { term: 'A camera', text: 'becomes a source of data.' },
      { term: 'Computer vision', text: 'transforms that data into perception.' },
      { term: 'Edge AI', text: 'enables faster local intelligence.' },
      { term: 'AI agents', text: 'can investigate and coordinate responses.' },
      { term: 'Digital Twins', text: 'can model systems and scenarios.' },
      { term: 'An AI OS', text: 'can help connect intelligence across applications, data and workflows.' },
    ] },
    { kind: 'p', text: 'The architecture becomes:' },
    { kind: 'flow', steps: ['SEE', 'UNDERSTAND', 'REASON', 'COORDINATE', 'ACT'] },
    { kind: 'p', text: 'That is the transition from a camera system to an intelligent system.' },
    { kind: 'statement', text: 'Vision captures the world. Intelligence determines what to do next.' },

    { kind: 'h2', id: 'future', text: 'The Future of Computer Vision' },
    { kind: 'p', text: 'Computer vision is moving beyond isolated image analysis.' },
    { kind: 'p', text: 'Future systems are likely to become increasingly:' },
    { kind: 'ul', items: ['real-time;', 'multimodal;', 'connected;', 'context-aware;', 'edge-enabled;', 'agent-driven.'] },
    { kind: 'p', text: 'Instead of analysing images independently, AI systems can combine visual information with language, sensors, enterprise data and operational context.' },
    { kind: 'p', text: 'A future industrial system may not simply identify a defect.' },
    { kind: 'p', text: 'It may understand:' },
    { kind: 'ul', items: [
      'what component is affected;', 'its maintenance history;', 'the potential operational impact;',
      'similar historical events;', 'available corrective actions.',
    ] },
    { kind: 'p', text: 'It could then coordinate the next approved step.' },
    { kind: 'p', text: 'The evolution is:' },
    { kind: 'flow', steps: ['Pixels', 'Objects', 'Events', 'Context', 'Intelligence', 'Action'] },
    { kind: 'p', text: 'This is where computer vision becomes a foundational component of autonomous systems.' },
  ],

  faqs: [
    { q: 'What is computer vision?', a: 'Computer vision is a field of artificial intelligence that enables machines to analyse and interpret information from images, video and other visual inputs.' },
    { q: 'How does computer vision work?', a: 'Computer vision systems capture visual data and use algorithms or AI models to identify patterns, objects, features, movement or anomalies. The resulting information can then support analysis, decisions or actions.' },
    { q: 'What is the difference between computer vision and image recognition?', a: 'Image recognition focuses primarily on identifying or classifying what is shown in an image. Computer vision is broader and can include object detection, tracking, segmentation, video analysis and spatial understanding.' },
    { q: 'Is computer vision the same as machine vision?', a: 'The terms are related but can be used differently. Machine vision often refers to vision systems used in industrial or automated inspection environments, while computer vision is the broader AI and computing field focused on enabling machines to interpret visual information.' },
    { q: 'What industries use computer vision?', a: 'Computer vision can be used in manufacturing, logistics, infrastructure, retail, healthcare, agriculture, transportation and other industries where visual information can support analysis or operations.' },
    { q: 'What is real-time computer vision?', a: 'Real-time computer vision refers to systems capable of analysing visual information quickly enough to support near-immediate insights or actions. Actual performance depends on the model, hardware, data pipeline and application requirements.' },
    { q: 'How does computer vision support autonomous intelligence?', a: 'Computer vision can provide the perception layer of an autonomous intelligence system. Visual events can be combined with contextual data, reasoning systems, AI agents and workflows to support decisions and approved actions.' },
  ],

  closing: {
    heading: 'Closing Perspective',
    paragraphs: [
      'Machines have always been able to capture images.',
      'The next step was teaching them to recognise what they were seeing.',
      'The more significant transformation is happening now.',
      'Visual information is becoming connected to context.',
      'Context is becoming intelligence.',
      'And intelligence is becoming connected to action.',
      'Computer vision gives AI the ability to observe.',
      'Combined with Edge AI, AI Agents, Digital Twins and intelligent orchestration, that perception can become part of a larger autonomous intelligence system.',
      'The future is not simply machines that can see. It is intelligent systems that can understand what they see—and know what to do next.',
    ],
  },

  cta: {
    headline: 'GIVE YOUR SYSTEMS THE ABILITY TO SEE.',
    body: 'Explore how Vision AI, Edge Intelligence, AI Agents and connected intelligence systems can transform visual data into operational understanding.',
    links: [
      { label: 'Explore Vision AI', to: '/products/vision-ai' },
      { label: 'Explore Deep Tech & Autonomous Intelligence', to: '/divisions/autonomous-intelligence' },
      { label: 'Explore the SVARA Ecosystem', to: '/ecosystem' },
    ],
  },

  related: [
    { label: 'Deep Tech & Autonomous Intelligence', to: '/divisions/autonomous-intelligence' },
    { label: 'Vision AI', to: '/products/vision-ai' },
    { label: 'Edge AI', to: '/products/edge-ai' },
    { label: 'Drone AI', to: '/products/drone-ai' },
    { label: 'AI Agents', to: '/products/ai-agents' },
    { label: 'Digital Twin', to: '/products/digital-twin' },
    { label: 'AI OS', to: '/products/ai-os' },
  ],
}
