// INSIGHT 04 — "What Are AI Agents?"
//
// Rendered in the broadsheet layout, which is now the default for every insight — see
// InsightLayout in ./types. Copy is VERBATIM from the approved draft.
//
// The governance material is the spine of this piece, not a disclaimer at the end: the
// autonomy-level ladder, the "what it must not do" line and the limits section are what
// separate it from the agent hype it is competing with. Do not trim them for length.
import type { Insight } from './types'

export const whatAreAiAgents: Insight = {
  slug: 'what-are-ai-agents',
  title: 'What Are AI Agents?',
  subtitle: 'Understanding the Systems That Can Reason, Use Tools and Take Action',
  seoTitle: 'What Are AI Agents? How Agentic AI Can Reason, Use Tools and Take Action',
  metaDescription:
    'AI agents are systems designed to pursue goals by reasoning, using tools and taking actions. Learn how AI agents work, how they differ from chatbots and their enterprise applications.',
  category: 'Deep Tech & Autonomous Intelligence',
  contentType: 'Pillar / Cluster Article',
  searchIntent: 'Informational',
  readingTime: '12–14 minutes',
  published: '2026-09-02',
  primaryKeywords: [
    'AI agents', 'what are AI agents', 'artificial intelligence agents',
    'agentic AI', 'autonomous AI agents',
  ],
  secondaryKeywords: [
    'AI agent architecture', 'AI agents vs chatbots', 'AI agents vs generative AI',
    'multi-agent systems', 'agentic workflows', 'enterprise AI agents',
    'AI orchestration', 'autonomous intelligence',
  ],
  dek: 'A chatbot responds. An agent pursues an objective — reasoning, using tools and acting within permissions. The shift is from AI that produces answers to AI that participates in work.',

  blocks: [
    { kind: 'h2', id: 'what-are-ai-agents', text: 'What Are AI Agents?' },
    { kind: 'p', text: 'AI agents are software systems designed to pursue an objective by interpreting information, reasoning about possible next steps, using available tools and taking actions within defined permissions and constraints.' },
    { kind: 'p', text: 'A traditional AI chatbot typically waits for a user to ask a question and then generates a response.' },
    { kind: 'p', text: 'An AI agent can potentially go further.' },
    { kind: 'p', text: 'Given an objective, an agent may be able to:' },
    { kind: 'ul', items: [
      'understand the task;', 'gather relevant information;', 'break the objective into smaller steps;',
      'select tools or systems to use;', 'execute actions;', 'evaluate the results;',
      'determine the next step;', 'repeat the process until the objective is completed or human intervention is required.',
    ] },
    { kind: 'p', text: 'This is one of the key ideas behind agentic AI.' },
    { kind: 'statement', text: 'A chatbot primarily responds. An AI agent is designed to pursue an objective.' },
    { kind: 'p', text: 'That does not mean every AI agent is fully autonomous.' },
    { kind: 'p', text: 'Autonomy exists on a spectrum. An agent may simply recommend actions, execute low-risk tasks automatically, or require human approval before taking consequential actions.' },
    { kind: 'p', text: 'The important shift is from AI that only produces answers toward AI that can participate in workflows and operations.' },

    { kind: 'h2', id: 'how-do-ai-agents-work', text: 'How Do AI Agents Work?' },
    { kind: 'p', text: 'An AI agent is not necessarily a single model.' },
    { kind: 'p', text: 'A functional agentic system can combine several components into a continuous operational loop.' },
    { kind: 'p', text: 'A simplified architecture looks like:' },
    { kind: 'flow', steps: ['Objective', 'Context', 'Reasoning', 'Planning', 'Tool Use', 'Action', 'Observation', 'Next Decision'] },
    { kind: 'p', text: 'Each component plays a different role.' },

    { kind: 'h3', id: 'objective', text: '1. Objective' },
    { kind: 'p', text: 'Every agent needs something to work toward.' },
    { kind: 'p', text: 'An objective might be:' },
    { kind: 'ul', items: [
      'resolve a customer request;', 'investigate an operational issue;', 'prepare a report;',
      'monitor a system;', 'identify potential risks;', 'coordinate a workflow;',
      'collect and analyse information.',
    ] },
    { kind: 'p', text: 'The objective provides direction.' },
    { kind: 'p', text: 'Without it, the system may generate useful information but has no clear definition of what it is trying to accomplish.' },

    { kind: 'h3', id: 'context', text: '2. Context' },
    { kind: 'p', text: 'Before acting, the agent needs relevant information.' },
    { kind: 'p', text: 'Context may come from:' },
    { kind: 'ul', items: [
      'enterprise databases;', 'documents;', 'knowledge systems;', 'APIs;',
      'previous interactions;', 'real-time data;', 'other AI systems.',
    ] },
    { kind: 'p', text: 'For example, an enterprise agent asked to investigate a delayed order may need access to:' },
    { kind: 'ul', items: ['order information;', 'inventory systems;', 'logistics data;', 'customer history;', 'operational policies.'] },
    { kind: 'p', text: 'The quality of an agent’s decisions depends significantly on whether it has the right context at the right time.' },

    { kind: 'h3', id: 'reasoning-and-planning', text: '3. Reasoning and Planning' },
    { kind: 'p', text: 'The agent evaluates the objective and available information to determine possible next steps.' },
    { kind: 'p', text: 'A complex objective may be broken into smaller tasks.' },
    { kind: 'p', text: 'For example:' },
    { kind: 'p', text: 'Investigate why production output has decreased.' },
    { kind: 'p', text: 'The agent might determine that it needs to:' },
    { kind: 'ul', items: [
      'retrieve recent production data;', 'compare it with historical performance;',
      'identify significant changes;', 'check machine or maintenance records;',
      'analyse possible contributing factors;', 'prepare findings.',
    ] },
    { kind: 'p', text: 'This process is often described as planning or agentic reasoning.' },
    { kind: 'p', text: 'The specific implementation varies. Not every system needs the same reasoning architecture, and production systems should avoid assuming that an agent’s generated plan is automatically correct.' },

    { kind: 'h3', id: 'tool-use', text: '4. Tool Use: Where AI Agents Become Operational' },
    { kind: 'p', text: 'One of the defining capabilities of an AI agent is the ability to interact with external tools and systems.' },
    { kind: 'p', text: 'Depending on permissions, an agent may use:' },
    { kind: 'ul', items: [
      'search and retrieval systems;', 'databases;', 'APIs;', 'CRMs;', 'ERP platforms;',
      'email systems;', 'calendars;', 'workflow engines;', 'code execution environments;', 'enterprise software.',
    ] },
    { kind: 'p', text: 'For example, instead of answering:' },
    { kind: 'p', text: '“You should create a support ticket.”' },
    { kind: 'p', text: 'An agent could potentially:' },
    { kind: 'flow', steps: ['retrieve the relevant information', 'create the ticket', 'assign it to the appropriate team', 'update the user'] },
    { kind: 'p', text: 'This is a fundamental transition.' },
    { kind: 'p', text: 'The AI is no longer only describing what should happen.' },
    { kind: 'p', text: 'It can become part of the system that makes it happen.' },
    { kind: 'statement', text: 'Language becomes an interface to action.' },

    { kind: 'h3', id: 'action', text: '5. Action' },
    { kind: 'p', text: 'After reasoning and selecting an appropriate tool, the agent can execute an action within its defined permissions.' },
    { kind: 'p', text: 'Actions may include:' },
    { kind: 'ul', items: [
      'retrieving information;', 'updating a record;', 'generating a document;', 'creating a task;',
      'sending a notification;', 'triggering a workflow;', 'assigning work;', 'interacting with another agent.',
    ] },
    { kind: 'p', text: 'The level of action should be determined by risk.' },
    { kind: 'p', text: 'For example:' },
    { kind: 'defs', items: [
      { term: 'Low-risk action', text: 'An agent formats a report.' },
      { term: 'Medium-risk action', text: 'An agent creates a support ticket.' },
      { term: 'Higher-risk action', text: 'An agent modifies a financial, operational or security-related system.' },
    ] },
    { kind: 'p', text: 'As the potential impact increases, governance and human approval can become increasingly important.' },

    { kind: 'h3', id: 'observation-and-feedback', text: '6. Observation and Feedback' },
    { kind: 'p', text: 'After an action is performed, the agent can evaluate the result.' },
    { kind: 'ul', items: [
      'Did the tool return the expected information?', 'Was the task completed?',
      'Did the action create a new problem?', 'Is another step required?',
    ] },
    { kind: 'p', text: 'This creates a feedback loop:' },
    { kind: 'flow', steps: ['Think', 'Act', 'Observe', 'Adapt'] },
    { kind: 'p', text: 'An agent may repeat this cycle multiple times while working toward its objective.' },

    { kind: 'h2', id: 'agents-vs-chatbots', text: 'AI Agents vs Chatbots' },
    { kind: 'p', text: 'The terms are often confused.' },
    { kind: 'p', text: 'A chatbot and an AI agent may both use similar language models, but their system design and operational role can be very different.' },
    { kind: 'table',
      caption: 'Capability comparison: AI chatbot and AI agent',
      headers: ['Capability', 'AI Chatbot', 'AI Agent'],
      rows: [
        ['Answers questions', '✓', '✓'],
        ['Generates content', '✓', '✓'],
        ['Maintains task context', 'Sometimes', '✓'],
        ['Uses external tools', 'Limited', 'Core capability'],
        ['Executes workflows', 'Usually limited', '✓'],
        ['Plans multi-step tasks', 'Limited', '✓'],
        ['Works toward an objective', 'Prompt-driven', 'Goal-driven'],
        ['Acts within permissions', 'Usually limited', 'Designed for this'],
        ['Coordinates with other agents', 'Rare', 'Possible'],
      ] },
    { kind: 'p', text: 'The distinction is not always absolute.' },
    { kind: 'p', text: 'A chatbot can be connected to tools.' },
    { kind: 'p', text: 'An AI agent can have a conversational interface.' },
    { kind: 'p', text: 'The more important question is:' },
    { kind: 'statement', text: 'Is the AI only generating a response, or is it participating in the process of achieving an objective?' },

    { kind: 'h2', id: 'agents-vs-generative-ai', text: 'AI Agents vs Generative AI' },
    { kind: 'p', text: 'Generative AI focuses on creating outputs.' },
    { kind: 'p', text: 'These outputs can include:' },
    { kind: 'ul', items: ['text;', 'images;', 'code;', 'audio;', 'video;', 'structured content.'] },
    { kind: 'p', text: 'AI agents may use generative AI as one of their underlying capabilities.' },
    { kind: 'p', text: 'However, an agent adds additional layers.' },
    { kind: 'p', text: 'A generative model may answer:' },
    { kind: 'p', text: '“Here is a strategy for reducing customer churn.”' },
    { kind: 'p', text: 'An AI agent could potentially:' },
    { kind: 'ul', items: [
      'analyse customer data;', 'identify high-risk accounts;', 'retrieve interaction history;',
      'generate recommended actions;', 'create follow-up tasks;', 'notify the appropriate team;', 'track the outcome.',
    ] },
    { kind: 'p', text: 'In this sense:' },
    { kind: 'statement', text: 'Generative AI can create. AI agents can coordinate creation with information, tools and action.' },

    { kind: 'h2', id: 'agentic-workflow', text: 'What Is an Agentic Workflow?' },
    { kind: 'p', text: 'An agentic workflow is a process in which AI agents participate in completing one or more stages of a task.' },
    { kind: 'p', text: 'For example:' },
    { kind: 'p', text: 'Objective: Analyse a market opportunity.' },
    { kind: 'p', text: 'An agentic workflow could involve:' },
    { kind: 'stack', layers: [
      { name: 'Research Agent', items: ['Collects relevant information'] },
      { name: 'Analysis Agent', items: ['Identifies patterns, opportunities and risks'] },
      { name: 'Strategy Agent', items: ['Develops possible recommendations'] },
      { name: 'Review Layer', items: ['Checks the output against defined criteria'] },
      { name: 'Human Decision-Maker', items: ['Approves, modifies or rejects high-impact recommendations'] },
    ] },
    { kind: 'p', text: 'This creates a workflow where intelligence is distributed across specialised functions.' },
    { kind: 'p', text: 'The architecture begins to resemble a digital organisation of specialised capabilities.' },

    { kind: 'h2', id: 'single-vs-multi-agent', text: 'Single-Agent vs Multi-Agent Systems' },
    { kind: 'p', text: 'Not every problem requires multiple agents.' },
    { kind: 'p', text: 'A simple task may be handled by a single well-designed agent.' },
    { kind: 'p', text: 'However, more complex workflows can potentially involve multiple specialised agents.' },
    { kind: 'defs', items: [
      { term: 'Single-Agent System', text: 'One agent handles a complete workflow. Example: retrieve sales data, analyse performance and prepare a report.' },
      { term: 'Multi-Agent System', text: 'Multiple agents perform specialised functions. Example: a Data Agent retrieves information, an Analysis Agent identifies patterns, a Research Agent gathers external context, an Operations Agent coordinates actions and a Review Agent checks outputs.' },
    ] },
    { kind: 'p', text: 'The value of a multi-agent architecture is not simply having more agents.' },
    { kind: 'p', text: 'More components can also introduce more complexity, latency and coordination challenges.' },
    { kind: 'p', text: 'The right architecture should be based on the problem being solved.' },
    { kind: 'statement', text: 'More agents do not automatically create more intelligence. Better orchestration does.' },

    { kind: 'h2', id: 'agent-architecture', text: 'AI Agent Architecture' },
    { kind: 'p', text: 'A production-grade AI agent can include several layers.' },
    { kind: 'defs', items: [
      { term: 'Intelligence Layer', text: 'The AI model or models responsible for interpreting information and generating reasoning or outputs.' },
      { term: 'Memory and State', text: 'Mechanisms for maintaining relevant information during or across tasks — short-term task state, conversation context, retrieved knowledge and approved long-term information.' },
      { term: 'Tool Layer', text: 'The interfaces that allow an agent to interact with external systems.' },
      { term: 'Planning Layer', text: 'The mechanisms used to break an objective into steps and determine the next action.' },
      { term: 'Orchestration Layer', text: 'The system responsible for coordinating agents, models, tools and workflows.' },
      { term: 'Governance Layer', text: 'The rules defining permissions, access, boundaries, approvals, monitoring and escalation.' },
    ] },
    { kind: 'p', text: 'Memory should not simply mean storing everything indefinitely. Systems need clear rules around what information is retained and why.' },
    { kind: 'p', text: 'Together, these components transform an AI model into a potentially operational intelligence system.' },

    { kind: 'h2', id: 'enterprise-agents', text: 'Enterprise AI Agents' },
    { kind: 'p', text: 'The most significant impact of AI agents may emerge inside organisations.' },
    { kind: 'p', text: 'Enterprise environments contain large numbers of repetitive but information-intensive workflows.' },
    { kind: 'p', text: 'Consider a simple request:' },
    { kind: 'p', text: '“Find out why this customer order is delayed.”' },
    { kind: 'p', text: 'A human employee may need to:' },
    { kind: 'ul', items: [
      'open a CRM;', 'check an order management system;', 'review inventory;',
      'contact logistics;', 'examine recent communications;', 'prepare a response.',
    ] },
    { kind: 'p', text: 'An AI agent could potentially coordinate parts of this process.' },
    { kind: 'p', text: 'It might:' },
    { kind: 'ul', items: [
      'retrieve the order;', 'identify its current status;', 'check inventory;',
      'retrieve logistics information;', 'analyse relevant events;', 'prepare a summary;',
      'draft a response;', 'request human approval when necessary.',
    ] },
    { kind: 'p', text: 'The goal is not necessarily to replace every person involved.' },
    { kind: 'p', text: 'It is to reduce the distance between:' },
    { kind: 'flow', steps: ['Question', 'Information', 'Decision', 'Action'] },

    { kind: 'h2', id: 'agents-in-autonomous-intelligence', text: 'AI Agents in Autonomous Intelligence' },
    { kind: 'p', text: 'AI agents can become the agency layer of an autonomous intelligence system.' },
    { kind: 'p', text: 'Consider a connected architecture.' },
    { kind: 'stack', layers: [
      { name: 'Perception', items: ['Vision AI and sensors observe the environment'] },
      { name: 'Local Intelligence', items: ['Edge AI processes information near the source'] },
      { name: 'Context', items: ['Enterprise systems and cloud infrastructure provide additional information'] },
      { name: 'Reasoning', items: ['AI models interpret the situation'] },
      { name: 'Agency', items: ['AI agents determine and coordinate next steps'] },
      { name: 'Action', items: ['Workflows, software systems, machines or people execute the response'] },
    ] },
    { kind: 'p', text: 'This creates a larger intelligence loop:' },
    { kind: 'flow', steps: ['Perceive', 'Understand', 'Reason', 'Coordinate', 'Act', 'Learn'] },
    { kind: 'p', text: 'An individual AI agent may be one component.' },
    { kind: 'p', text: 'A network of connected technologies can create the broader autonomous system.' },

    { kind: 'h2', id: 'what-can-agents-do', text: 'What Can AI Agents Do?' },
    { kind: 'p', text: 'AI agents can potentially support a wide range of functions.' },
    { kind: 'defs', items: [
      { term: 'Research and Knowledge Work', text: 'Retrieve information, analyse documents, synthesise findings and prepare structured outputs.' },
      { term: 'Customer Operations', text: 'Investigate requests, retrieve account information, prepare responses and trigger approved workflows.' },
      { term: 'Business Operations', text: 'Help coordinate reporting, task management, document workflows and operational analysis.' },
      { term: 'Software and Engineering', text: 'Assist with code analysis, testing, debugging, documentation and development workflows.' },
      { term: 'Physical Operations', text: 'When connected to Vision AI, Edge AI, sensors and operational systems, participate in workflows that connect digital intelligence to physical environments.' },
    ] },

    { kind: 'h2', id: 'limits', text: 'The Limits of AI Agents' },
    { kind: 'p', text: 'AI agents should not be treated as universally reliable autonomous employees.' },
    { kind: 'p', text: 'They have limitations.' },
    { kind: 'defs', items: [
      { term: 'Incorrect Reasoning', text: 'An agent can misunderstand a task or reach an incorrect conclusion.' },
      { term: 'Tool Errors', text: 'An external system may return incomplete or incorrect information.' },
      { term: 'Context Gaps', text: 'The agent may not have access to all relevant information.' },
      { term: 'Permission Risks', text: 'Giving an agent access to powerful systems without appropriate controls can create operational risk.' },
      { term: 'Unpredictable Behaviour', text: 'Complex workflows can produce unexpected outcomes, particularly when agents interact with multiple tools or other agents.' },
    ] },
    { kind: 'p', text: 'For this reason, agentic capability must be matched with governance.' },

    { kind: 'h2', id: 'human-in-the-loop', text: 'Human-in-the-Loop AI Agents' },
    { kind: 'p', text: 'A useful model for enterprise AI is not complete autonomy.' },
    { kind: 'p', text: 'It is adaptive autonomy.' },
    { kind: 'p', text: 'The level of human involvement can depend on the situation.' },
    { kind: 'defs', items: [
      { term: 'Level 1 — Assist', text: 'The AI provides information or recommendations.' },
      { term: 'Level 2 — Prepare', text: 'The AI performs work but requires approval before an action is finalised.' },
      { term: 'Level 3 — Execute Within Boundaries', text: 'The AI performs approved low-risk actions independently.' },
      { term: 'Level 4 — Escalate Exceptions', text: 'The AI handles normal situations and brings unusual or high-impact cases to humans.' },
    ] },
    { kind: 'p', text: 'This creates a more realistic approach to autonomous intelligence.' },
    { kind: 'statement', text: 'The objective is not maximum autonomy. It is appropriate autonomy.' },

    { kind: 'h2', id: 'governance', text: 'Governance: Who Controls the Agent?' },
    { kind: 'p', text: 'As AI agents gain access to tools and systems, governance becomes critical.' },
    { kind: 'p', text: 'Every enterprise should consider questions such as:' },
    { kind: 'ul', items: [
      'What information can the agent access?', 'Which tools can it use?', 'What actions can it execute?',
      'What actions require human approval?', 'How are actions recorded?', 'How can an action be reversed?',
      'What happens when the agent encounters uncertainty?', 'Who is accountable for the system?',
    ] },
    { kind: 'p', text: 'A capable AI agent without clear boundaries can become an operational risk.' },
    { kind: 'p', text: 'A well-designed AI agent should understand not only what it can do, but also:' },
    { kind: 'statement', text: 'What it must not do.' },

    { kind: 'h2', id: 'svara-perspective', text: 'The SVARA Perspective: AI Agents as Digital Agency' },
    { kind: 'p', text: 'For SVARA, AI agents represent an important layer in the evolution from AI tools to connected intelligence systems.' },
    { kind: 'defs', items: [
      { term: 'A Vision AI system', text: 'can see.' },
      { term: 'An Edge AI system', text: 'can process locally.' },
      { term: 'Generative and Cognitive AI', text: 'can interpret and reason.' },
      { term: 'Digital Twins', text: 'can simulate and model.' },
      { term: 'AI Agents', text: 'can coordinate tasks and actions.' },
      { term: 'An AI OS', text: 'can help orchestrate the entire intelligence environment.' },
    ] },
    { kind: 'p', text: 'The architecture becomes:' },
    { kind: 'flow', steps: ['Data', 'Perception', 'Intelligence', 'Agency', 'Action'] },
    { kind: 'p', text: 'The agent is not the entire system.' },
    { kind: 'p', text: 'It is part of the bridge between intelligence and execution.' },
    { kind: 'statement', text: 'AI becomes truly operational when it can move from understanding what should happen to participating in making it happen.' },

    { kind: 'h2', id: 'future', text: 'What Is the Future of AI Agents?' },
    { kind: 'p', text: 'The next generation of AI systems is likely to become increasingly:' },
    { kind: 'ul', items: ['specialised;', 'connected;', 'multimodal;', 'tool-enabled;', 'context-aware;', 'governed;', 'collaborative.'] },
    { kind: 'p', text: 'Rather than relying on one AI system to perform every task, organisations may increasingly deploy networks of specialised intelligence.' },
    { kind: 'ul', items: ['One agent may analyse.', 'Another may retrieve.', 'Another may simulate.', 'Another may coordinate.', 'Another may review.'] },
    { kind: 'p', text: 'Humans remain responsible for defining objectives, establishing boundaries and governing high-impact decisions.' },
    { kind: 'p', text: 'The long-term opportunity is not to create an AI that replaces every process.' },
    { kind: 'p', text: 'It is to redesign how intelligence participates in those processes.' },
    { kind: 'p', text: 'The evolution may look like this:' },
    { kind: 'ol', items: [
      'Software executes instructions.', 'Automation follows workflows.', 'Generative AI creates outputs.',
      'AI Agents pursue objectives.', 'Autonomous intelligence connects perception, reasoning, agency and action.',
    ] },
  ],

  faqs: [
    { q: 'What is an AI agent?', a: 'An AI agent is a software system designed to pursue an objective by processing information, reasoning about possible next steps, using available tools and taking actions within defined permissions and constraints.' },
    { q: 'How are AI agents different from chatbots?', a: 'Chatbots primarily focus on responding to user input. AI agents can additionally use tools, perform multi-step tasks, maintain task state and participate in workflows designed to achieve an objective.' },
    { q: 'Are AI agents autonomous?', a: 'The level of autonomy varies. Some agents only make recommendations, while others can execute approved actions independently. Higher-impact decisions may require human review or approval.' },
    { q: 'What is agentic AI?', a: 'Agentic AI refers broadly to AI systems designed to pursue goals through processes such as planning, reasoning, tool use, action and feedback.' },
    { q: 'What is a multi-agent system?', a: 'A multi-agent system uses multiple specialised AI agents that can perform different tasks and coordinate as part of a larger workflow.' },
    { q: 'Can AI agents use enterprise software?', a: 'Yes, when appropriately integrated and authorised. AI agents can potentially interact with enterprise systems through APIs, tools and workflow integrations.' },
    { q: 'What is the biggest risk with AI agents?', a: 'One major challenge is giving an AI system the ability to take actions without appropriate governance. Permissions, monitoring, human oversight and clear operating boundaries are essential.' },
  ],

  closing: {
    heading: 'Closing Perspective',
    paragraphs: [
      'The most important development in AI may not be the ability to generate increasingly convincing answers.',
      'It may be the ability to connect intelligence to work.',
      'AI agents represent a transition from “What can AI tell me?” to “What can AI help me accomplish?”',
      'But capability alone is not enough.',
      'The future of agentic AI depends on building systems that are not only intelligent—but also connected, observable, governed and aligned with human objectives.',
      'The future is not simply AI that can think.',
      'It is intelligence that can understand, coordinate and act—responsibly.',
    ],
  },

  cta: {
    headline: 'TURN INTELLIGENCE INTO ACTION.',
    body: 'Explore how AI Agents can connect data, reasoning, enterprise systems and workflows—forming the agency layer of next-generation autonomous intelligence.',
    links: [
      { label: 'Explore AI Agents', to: '/products/ai-agents' },
      { label: 'Explore Generative & Cognitive AI', to: '/technologies' },
      { label: 'Explore AI OS', to: '/products/ai-os' },
      { label: 'Explore the SVARA Ecosystem', to: '/ecosystem' },
    ],
  },

  related: [
    { label: 'What Is Autonomous Intelligence?', to: '/insights/autonomous-intelligence' },
    { label: 'Computer Vision Explained', to: '/insights/what-is-computer-vision' },
    { label: 'Edge AI vs Cloud AI', to: '/insights/edge-ai-vs-cloud-ai' },
    { label: 'AI Agents', to: '/products/ai-agents' },
    { label: 'AI OS', to: '/products/ai-os' },
    { label: 'Vision AI', to: '/products/vision-ai' },
    { label: 'Edge AI', to: '/products/edge-ai' },
    { label: 'Digital Twin', to: '/products/digital-twin' },
    { label: 'Deep Tech & Autonomous Intelligence', to: '/divisions/autonomous-intelligence' },
  ],
}
